<?php
declare(strict_types=1);
session_start();
$erpRoot=dirname(__DIR__,3);
if(!is_file($erpRoot.'/config.php')){http_response_code(503);exit('Falta config.php. Copiá config.example.php como config.php y completalo.');}
$cfg=require $erpRoot.'/config.php';
date_default_timezone_set($cfg['timezone']??'America/Argentina/Buenos_Aires');
try{$db=new PDO('mysql:host='.$cfg['db_host'].';dbname='.$cfg['db_name'].';charset=utf8mb4',$cfg['db_user'],$cfg['db_pass'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);}catch(Throwable $e){http_response_code(500);exit('No se pudo conectar con MySQL. Revisá config.php.');}
if(isset($_SESSION['last'])&&time()-$_SESSION['last']>(int)$cfg['session_minutes']*60){session_unset();session_destroy();session_start();$_SESSION['msg']='La sesión se cerró por inactividad.';}
$_SESSION['last']=time(); $_SESSION['csrf']??=bin2hex(random_bytes(24));
function e($s):string{return htmlspecialchars((string)$s,ENT_QUOTES,'UTF-8');}
function mon($n,string $currency='ARS'):string{$prefix=$currency==='USD'?'US$ ':'$ ';return $prefix.number_format((float)$n,2,',','.');}
function go(string $url='index.php'):never{header('Location: '.$url);exit;}
function msg(string $s):void{$_SESSION['msg']=$s;}
function csrf():void{if(!hash_equals($_SESSION['csrf'],$_POST['csrf']??'')){http_response_code(419);exit('Solicitud vencida.');}}
function isAdmin():bool{return ($_SESSION['user']['role']??'')==='admin';}
function fileUp(string $key,string $prefix):?string{
 if(empty($_FILES[$key]['name']))return null;
 if($_FILES[$key]['error']!==UPLOAD_ERR_OK||$_FILES[$key]['size']>8388608)throw new Exception('Archivo inválido o mayor a 8 MB.');
 $mime=(new finfo(FILEINFO_MIME_TYPE))->file($_FILES[$key]['tmp_name']);$ext=['application/pdf'=>'pdf','image/jpeg'=>'jpg','image/png'=>'png'][$mime]??null;
 if(!$ext)throw new Exception('Solo se permiten PDF, JPG o PNG.');
 $name=$prefix.'-'.bin2hex(random_bytes(8)).'.'.$ext;
 $root=dirname(__DIR__,3);
 if(!move_uploaded_file($_FILES[$key]['tmp_name'],$root.'/storage/uploads/'.$name))throw new Exception('No se pudo guardar el archivo.');
 return 'storage/uploads/'.$name;
}
function top(string $title):void{$u=$_SESSION['user']??null;$m=$_SESSION['msg']??null;unset($_SESSION['msg']);?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($title)?> · Punto ERP</title>
<style>
:root{--o:#ff6702;--dark:#171b20;--ink:#27303b;--muted:#6e7781;--line:#e1e5e9;--bg:#f4f6f8;--green:#15815c;--red:#bf3c3c}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.45 system-ui,-apple-system,Segoe UI,sans-serif}header{min-height:68px;padding:0 5%;background:var(--dark);color:#fff;display:flex;align-items:center;justify-content:space-between}header b{font-size:19px}header b i{color:var(--o);font-style:normal}nav a{color:#fff;text-decoration:none;margin-left:20px}.wrap{max-width:1180px;margin:28px auto;padding:0 18px}.card{background:#fff;border:1px solid var(--line);border-radius:14px;padding:22px;margin-bottom:18px;box-shadow:0 4px 16px #00000008}.grid{display:grid;grid-template-columns:repeat(12,1fr);gap:16px}.c3{grid-column:span 3}.c4{grid-column:span 4}.c6{grid-column:span 6}.c8{grid-column:span 8}.c12{grid-column:span 12}label{display:block;font-weight:650;margin-bottom:6px}input,select,textarea{width:100%;padding:10px 11px;border:1px solid #cbd1d7;border-radius:8px;background:#fff;font:inherit}textarea{min-height:80px}.btn{display:inline-block;border:0;border-radius:8px;padding:10px 15px;background:var(--o);color:#fff;text-decoration:none;font-weight:700;cursor:pointer}.btn.light{background:#edf0f3;color:var(--ink)}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:11px 9px;border-bottom:1px solid var(--line);vertical-align:top}th{font-size:12px;text-transform:uppercase;color:var(--muted)}.right{text-align:right}.muted{color:var(--muted)}.pill{display:inline-block;padding:4px 9px;border-radius:20px;background:#edf0f3;font-size:12px}.kpi{font-size:26px;font-weight:760;margin-top:6px}.ok{color:var(--green)}.bad{color:var(--red)}.actions{display:flex;gap:9px;align-items:center;flex-wrap:wrap}.flash{padding:12px 16px;background:#fff0e5;border:1px solid #ffd2b1;border-radius:9px;margin-bottom:18px}.login{max-width:430px;margin:9vh auto}.scroll{overflow:auto}@media(max-width:760px){.c3,.c4,.c6,.c8{grid-column:span 12}header{padding:15px 20px;align-items:flex-start;flex-direction:column}nav{padding-top:9px}nav a{margin:0 12px 0 0}}
</style></head><body><?php if($u):?><header><b><i>●</i> Punto ERP</b><nav><a href="index.php">Panel</a>
<a href="?a=clients">Clientes</a><a href="?a=partners">Arquitectos y constructoras</a>
<a href="?a=projects">Proyectos</a><a href="?a=receipts">Recibos</a><?php if(isAdmin()):?><a href="?a=users">Usuarios</a><?php endif;?><a href="?a=logout">Salir</a></nav></header><?php endif;?><main class="wrap"><?php if($m):?><div class="flash"><?=e($m)?></div><?php endif;?><?php }
function bottom():void{?></main></body></html><?php }
function token():string{return '<input type="hidden" name="csrf" value="'.e($_SESSION['csrf']).'">';}
function receipt(PDO $db,array $cfg,array $p,bool $public=false):never{
 $s=$db->prepare('SELECT a.amount,c.description FROM allocations a JOIN charges c ON c.id=a.charge_id WHERE a.payment_id=?');$s->execute([$p['id']]);$items=$s->fetchAll();
 ?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title><?=e($p['receipt_number'])?></title><style>body{font:15px/1.5 system-ui;color:#202832;background:#eee;margin:0}.sheet{max-width:760px;margin:32px auto;background:#fff;padding:42px;border-top:8px solid #ff6702}.head{display:flex;justify-content:space-between;border-bottom:1px solid #ddd;padding-bottom:22px}.brand{font-size:24px;font-weight:800}.orange{color:#ff6702}.num{text-align:right}.amount{font-size:30px;font-weight:800;margin:25px 0}table{width:100%;border-collapse:collapse}td{padding:10px;border-bottom:1px solid #eee}.right{text-align:right}.foot{margin-top:35px;color:#69727d}.actions{max-width:760px;margin:18px auto;text-align:right}.btn{display:inline-block;padding:10px 15px;background:#202832;color:#fff;text-decoration:none;border:0;border-radius:7px;cursor:pointer}@media print{body{background:#fff}.sheet{margin:0;max-width:none}.actions{display:none}}</style></head><body><div class="actions"><button class="btn" onclick="window.print()">Imprimir / Guardar PDF</button></div><div class="sheet"><div class="head"><div><div class="brand"><span class="orange">●</span> <?=e($cfg['company_name']??'Punto ERP')?></div><div><?=e($cfg['company_address']??'')?></div><div><?=e($cfg['company_cuit']??'')?></div></div><div class="num"><b>RECIBO</b><br><?=e($p['receipt_number'])?><br><?=e(date('d/m/Y',strtotime($p['payment_date'])))?><br><?=e($p['currency'])?></div></div><p>Recibimos de <b><?=e($p['business_name'])?></b><?php if($p['cuit']):?> · CUIT <?=e($p['cuit'])?><?php endif;?> la suma de:</p><div class="amount"><?=mon($p['amount'],$p['currency'])?></div><p>Correspondiente al proyecto <b><?=e($p['project_number'])?> · <?=e($p['project_name'])?></b>.</p><table><?php foreach($items as $i):?><tr><td><?=e($i['description'])?></td><td class="right"><?=mon($i['amount'],$p['currency'])?></td></tr><?php endforeach;?><?php $allocated=array_sum(array_column($items,'amount'));if($p['amount']-$allocated>0.009):?><tr><td>Pago pendiente de imputación</td><td class="right"><?=mon($p['amount']-$allocated,$p['currency'])?></td></tr><?php endif;?></table><p><b>Medio de pago:</b> <?=e(ucfirst($p['method']))?><?php if($p['reference']):?> · Referencia <?=e($p['reference'])?><?php endif;?></p><div class="foot">Este recibo acredita la recepción del pago indicado. Conservá este comprobante.</div></div></body></html><?php exit;
}
function replaceCharge(PDO $db,int $projectId,int $newChargeId,array $types,string $quoteCategory='general',string $currency='ARS'):void{
 $marks=implode(',',array_fill(0,count($types),'?'));
 $s=$db->prepare("SELECT c.id FROM charges c LEFT JOIN quotes q ON q.id=c.quote_id WHERE c.project_id=? AND c.active=1 AND c.id<>? AND c.type IN ($marks) AND COALESCE(q.quote_category,'general')=? AND c.currency=?");
 $s->execute(array_merge([$projectId,$newChargeId],$types,[$quoteCategory,$currency]));
 foreach($s as $old){
  $als=$db->prepare('SELECT payment_id,amount FROM allocations WHERE charge_id=?');$als->execute([$old['id']]);
  foreach($als as $al)$db->prepare('INSERT INTO allocations(payment_id,charge_id,amount) VALUES(?,?,?) ON DUPLICATE KEY UPDATE amount=amount+VALUES(amount)')->execute([$al['payment_id'],$newChargeId,$al['amount']]);
  $db->prepare('DELETE FROM allocations WHERE charge_id=?')->execute([$old['id']]);
  $db->prepare('UPDATE charges SET active=0 WHERE id=?')->execute([$old['id']]);
 }
}
$a=$_GET['a']??'dashboard';
try{$count=(int)$db->query('SELECT COUNT(*) FROM users')->fetchColumn();}catch(Throwable $e){exit('Importá schema.sql en phpMyAdmin antes de continuar.');}
if($a==='public_receipt'&&!empty($_GET['token'])){$s=$db->prepare('SELECT p.*,pr.project_number,pr.name project_name,c.business_name,c.cuit FROM payments p JOIN projects pr ON pr.id=p.project_id JOIN clients c ON c.id=pr.client_id WHERE p.public_token=?');$s->execute([$_GET['token']]);$p=$s->fetch();if(!$p){http_response_code(404);exit('Recibo inexistente.');}receipt($db,$cfg,$p,true);}
if($a==='setup'&&!$count){
 if($_SERVER['REQUEST_METHOD']==='POST'){csrf();if(strlen($_POST['password'])<8)throw new Exception('La clave debe tener 8 caracteres.');$db->prepare('INSERT INTO users(name,email,password_hash) VALUES(?,?,?)')->execute([trim($_POST['name']),strtolower(trim($_POST['email'])),password_hash($_POST['password'],PASSWORD_DEFAULT)]);msg('Administrador creado.');go();}
 top('Configuración');?><div class="login card"><h1>Crear administrador</h1><form method="post"><?=token()?><p><label>Nombre</label><input name="name" required></p>
<p><label>Email</label><input type="email" name="email" required></p>
<p><label>Clave</label><input type="password" name="password" minlength="8" required></p><button class="btn">Crear cuenta</button></form></div><?php bottom();exit;
}
if($a==='logout'){session_unset();session_destroy();go();}
if(empty($_SESSION['user'])){
 if(!$count)go('?a=setup');
 if($_SERVER['REQUEST_METHOD']==='POST'){csrf();$s=$db->prepare('SELECT * FROM users WHERE email=? AND active=1');$s->execute([strtolower(trim($_POST['email']))]);$u=$s->fetch();if($u&&password_verify($_POST['password'],$u['password_hash'])){session_regenerate_id(true);$_SESSION['user']=['id'=>$u['id'],'name'=>$u['name'],'role'=>$u['role']];go();}msg('Email o clave incorrectos.');go();}
 top('Ingresar');?><div class="login card"><h1>Punto ERP</h1><p class="muted">Cuentas de clientes y proyectos</p><form method="post"><?=token()?><p><label>Email</label><input type="email" name="email" required autofocus></p>
<p><label>Clave</label><input type="password" name="password" required></p><button class="btn">Ingresar</button></form></div><?php bottom();exit;
}
if($_SERVER['REQUEST_METHOD']==='POST'&&!isAdmin()){http_response_code(403);exit('Usuario de consulta: no puede modificar datos.');}
try{
 if($a==='save_client'){csrf();$email=strtolower(trim($_POST['email']??''));if($email!==''&&!filter_var($email,FILTER_VALIDATE_EMAIL))throw new Exception('El email ingresado no es válido.');$allowedIva=['responsable_inscripto','monotributista','exento','consumidor_final','no_responsable'];$iva=$_POST['iva_condition']??'';if(!in_array($iva,$allowedIva,true))throw new Exception('Seleccioná una condición frente al IVA.');$db->prepare('INSERT INTO clients(business_name,contact_name,cuit,iva_condition,email,whatsapp,address,city,province,country,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?)')->execute([trim($_POST['business_name']),trim($_POST['contact_name']),trim($_POST['cuit']),$iva,$email,trim($_POST['whatsapp']),trim($_POST['address']),trim($_POST['city']),trim($_POST['province']),trim($_POST['country'])?:'Argentina',trim($_POST['notes'])]);msg('Cliente creado.');go('?a=clients');}
 if($a==='update_client'){csrf();$id=(int)($_POST['client_id']??0);$name=trim($_POST['business_name']??'');$email=strtolower(trim($_POST['email']??''));if($name==='')throw new Exception('Ingresá el nombre del cliente o razón social.');if($email!==''&&!filter_var($email,FILTER_VALIDATE_EMAIL))throw new Exception('El email ingresado no es válido.');$allowedIva=['responsable_inscripto','monotributista','exento','consumidor_final','no_responsable'];$iva=$_POST['iva_condition']??'';if(!in_array($iva,$allowedIva,true))throw new Exception('Seleccioná una condición frente al IVA.');$active=isset($_POST['active'])?1:0;$s=$db->prepare('UPDATE clients SET business_name=?,contact_name=?,cuit=?,iva_condition=?,email=?,whatsapp=?,address=?,city=?,province=?,country=?,notes=?,active=? WHERE id=?');$s->execute([$name,trim($_POST['contact_name']),trim($_POST['cuit']),$iva,$email,trim($_POST['whatsapp']),trim($_POST['address']),trim($_POST['city']),trim($_POST['province']),trim($_POST['country'])?:'Argentina',trim($_POST['notes']),$active,$id]);if(!$s->rowCount()){$check=$db->prepare('SELECT COUNT(*) FROM clients WHERE id=?');$check->execute([$id]);if(!(int)$check->fetchColumn())throw new Exception('El cliente no existe.');}msg('Cliente actualizado.');go('?a=clients');}
 if($a==='save_partner'){csrf();$email=strtolower(trim($_POST['email']??''));if($email!==''&&!filter_var($email,FILTER_VALIDATE_EMAIL))throw new Exception('El email ingresado no es válido.');$types=['arquitecto','estudio_arquitectura','constructora','desarrolladora','otro'];$type=$_POST['partner_type']??'';if(!in_array($type,$types,true))throw new Exception('Seleccioná un tipo válido.');$name=trim($_POST['business_name']??'');if($name==='')throw new Exception('Ingresá el nombre o razón social.');$db->prepare('INSERT INTO project_partners(partner_type,business_name,contact_name,cuit,email,whatsapp,address,city,province,country,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?)')->execute([$type,$name,trim($_POST['contact_name']),trim($_POST['cuit']),$email,trim($_POST['whatsapp']),trim($_POST['address']),trim($_POST['city']),trim($_POST['province']),trim($_POST['country'])?:'Argentina',trim($_POST['notes'])]);msg('Arquitecto o constructora guardado.');go('?a=partners');}
 if($a==='save_project'){csrf();$partnerId=(int)($_POST['partner_id']??0)?:null;$db->prepare('INSERT INTO projects(client_id,partner_id,project_number,name,status,currency,tax_mode,vat_rate,engineering_pct,notes) VALUES(?,?,?,?,?,\'ARS\',\'sin_iva\',21,10,?)')->execute([$_POST['client_id'],$partnerId,trim($_POST['project_number']),trim($_POST['name']),$_POST['status'],trim($_POST['notes'])]);$id=$db->lastInsertId();msg('Proyecto creado. Ahora podés cargar sus presupuestos por rubro.');go('?a=project&id='.$id);}
 if($a==='update_project'){
  csrf();$pid=(int)($_POST['project_id']??0);$status=$_POST['status']??'consulta';
  if(!in_array($status,['consulta','presupuestado','aprobado','en_obra','finalizado','cancelado'],true))throw new Exception('Seleccioná un estado válido.');
  $s=$db->prepare('SELECT id FROM projects WHERE id=?');$s->execute([$pid]);if(!$s->fetch())throw new Exception('El proyecto no existe.');
  $partnerId=(int)($_POST['partner_id']??0)?:null;$db->prepare('UPDATE projects SET client_id=?,partner_id=?,project_number=?,name=?,status=?,notes=? WHERE id=?')->execute([(int)$_POST['client_id'],$partnerId,trim($_POST['project_number']),trim($_POST['name']),$status,trim($_POST['notes']),$pid]);
  msg('Proyecto actualizado.');go('?a=project&id='.$pid);
 }
 if($a==='save_quote'){csrf();$pid=(int)$_POST['project_id'];$categories=['domotica'=>'Domótica','redes'=>'Redes','camaras'=>'Cámaras','alarma'=>'Alarma','audio'=>'Audio'];$category=$_POST['quote_category']??'';if(!isset($categories[$category]))throw new Exception('Seleccioná el rubro del presupuesto.');$currency=$_POST['currency']??'';if(!in_array($currency,['ARS','USD'],true))throw new Exception('Seleccioná la moneda del presupuesto.');$taxMode=$_POST['tax_mode']??'';if(!in_array($taxMode,['sin_iva','iva_incluido','mas_iva'],true))throw new Exception('Seleccioná una modalidad de IVA válida.');$materials=(float)$_POST['materials_amount'];$labor=(float)$_POST['labor_amount'];$base=$materials+$labor;$factor=$taxMode==='mas_iva'?1+(float)$_POST['vat_rate']/100:1;$materialsTotal=round($materials*$factor,2);$laborTotal=round($labor*$factor,2);$total=$materialsTotal+$laborTotal;$file=fileUp('quote_file','presupuesto-'.$category);$db->beginTransaction();$db->prepare('INSERT INTO quotes(project_id,version_no,quote_category,currency,quote_date,materials_amount,labor_amount,subtotal,tax_mode,vat_rate,total,status,file_path,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$pid,$_POST['version_no'],$category,$currency,$_POST['quote_date'],$materials,$labor,$base,$taxMode,$_POST['vat_rate'],$total,$_POST['status'],$file,trim($_POST['notes'])]);$qid=(int)$db->lastInsertId();$categoryLabel=$categories[$category];
  if($_POST['status']==='aprobado_inicial'){$amt=round($total*(float)$_POST['engineering_pct']/100,2);$db->prepare("INSERT INTO charges(project_id,quote_id,charge_date,type,currency,description,amount) VALUES(?,?,?,'ingenieria',?,?,?)")->execute([$pid,$qid,$_POST['quote_date'],$currency,'Adelanto de ingeniería '.$_POST['engineering_pct'].'% · '.$categoryLabel.' · v'.$_POST['version_no'],$amt]);$eng=(int)$db->lastInsertId();replaceCharge($db,$pid,$eng,['ingenieria'],$category,$currency);$db->prepare("UPDATE projects SET status='aprobado' WHERE id=?")->execute([$pid]);}
  if($_POST['status']==='final'){$db->prepare("INSERT INTO charges(project_id,quote_id,charge_date,type,currency,description,amount) VALUES(?,?,?,'materiales',?,?,?)")->execute([$pid,$qid,$_POST['quote_date'],$currency,'Materiales · '.$categoryLabel.' · presupuesto final v'.$_POST['version_no'],$materialsTotal]);$mat=(int)$db->lastInsertId();replaceCharge($db,$pid,$mat,['materiales'],$category,$currency);$db->prepare("INSERT INTO charges(project_id,quote_id,charge_date,type,currency,description,amount) VALUES(?,?,?,'mano_obra',?,?,?)")->execute([$pid,$qid,$_POST['quote_date'],$currency,'Mano de obra · '.$categoryLabel.' · presupuesto final v'.$_POST['version_no'],$laborTotal]);$laborCharge=(int)$db->lastInsertId();replaceCharge($db,$pid,$laborCharge,['ingenieria','mano_obra','obra'],$category,$currency);$db->prepare("UPDATE projects SET status='en_obra' WHERE id=?")->execute([$pid]);}
  $db->commit();msg('Presupuesto cargado.');go('?a=project&id='.$pid);
 }
 if($a==='save_charge'){csrf();$currency=$_POST['currency']??'';if(!in_array($currency,['ARS','USD'],true))throw new Exception('Seleccioná la moneda del cargo.');$db->prepare('INSERT INTO charges(project_id,charge_date,type,currency,description,amount) VALUES(?,?,?,?,?,?)')->execute([$_POST['project_id'],$_POST['charge_date'],$_POST['type'],$currency,trim($_POST['description']),$_POST['amount']]);msg('Cargo agregado.');go('?a=project&id='.$_POST['project_id']);}
 if($a==='save_payment'){
  csrf();$pid=(int)$_POST['project_id'];$currency=$_POST['currency']??'';if(!in_array($currency,['ARS','USD'],true))throw new Exception('Seleccioná la moneda del pago.');$amount=(float)$_POST['amount'];if($amount<=0)throw new Exception('El importe debe ser mayor a cero.');$receiptFile=fileUp('receipt','pago');
  $s=$db->prepare("SELECT c.id,c.type,c.amount-COALESCE(SUM(a.amount),0) due FROM charges c LEFT JOIN allocations a ON a.charge_id=c.id WHERE c.project_id=? AND c.currency=? AND c.active=1 GROUP BY c.id HAVING due>0.009 ORDER BY FIELD(c.type,'ingenieria','mano_obra','materiales','adicional','ajuste'),c.charge_date,c.id");$s->execute([$pid,$currency]);$open=[];foreach($s as $charge)$open[(int)$charge['id']]=(float)$charge['due'];
  $alloc=[];foreach($_POST['alloc']??[] as $cid=>$value){$cid=(int)$cid;$value=(float)$value;if($value<=0)continue;if(!isset($open[$cid]))throw new Exception('Uno de los cargos ya no está disponible.');if($value>$open[$cid]+.001)throw new Exception('La imputación supera el pendiente del cargo.');$alloc[$cid]=$value;}
  $allocated=array_sum($alloc);if($allocated>$amount+.001)throw new Exception('La imputación supera el pago.');$remaining=$amount-$allocated;
  foreach($open as $cid=>$due){if($remaining<=.009)break;$available=$due-($alloc[$cid]??0);if($available<=.009)continue;$auto=min($available,$remaining);$alloc[$cid]=($alloc[$cid]??0)+$auto;$remaining-=$auto;}
  $db->beginTransaction();$publicToken=bin2hex(random_bytes(24));$db->prepare('INSERT INTO payments(project_id,currency,payment_date,amount,method,reference,notes,receipt_path,public_token) VALUES(?,?,?,?,?,?,?,?,?)')->execute([$pid,$currency,$_POST['payment_date'],$amount,$_POST['method'],trim($_POST['reference']),trim($_POST['notes']),$receiptFile,$publicToken]);$pay=(int)$db->lastInsertId();$receiptNumber='REC-'.date('Y',strtotime($_POST['payment_date'])).'-'.str_pad((string)$pay,6,'0',STR_PAD_LEFT);$db->prepare('UPDATE payments SET receipt_number=? WHERE id=?')->execute([$receiptNumber,$pay]);foreach($alloc as $cid=>$value)$db->prepare('INSERT INTO allocations(payment_id,charge_id,amount) VALUES(?,?,?)')->execute([$pay,$cid,$value]);$db->commit();msg('Pago registrado, imputado y recibo '.$receiptNumber.' generado.');go('?a=project&id='.$pid);
 }
 if($a==='send_receipt_email'){csrf();$id=(int)$_POST['payment_id'];$s=$db->prepare('SELECT p.*,pr.project_number,pr.name project_name,c.business_name,c.email FROM payments p JOIN projects pr ON pr.id=p.project_id JOIN clients c ON c.id=pr.client_id WHERE p.id=?');$s->execute([$id]);$p=$s->fetch();if(!$p||!filter_var($p['email'],FILTER_VALIDATE_EMAIL))throw new Exception('El cliente no tiene un email válido.');$url=rtrim($cfg['base_url'],'/').'/?a=public_receipt&token='.$p['public_token'];$subject='Recibo '.$p['receipt_number'].' · Punto ERP';$html='<p>Hola, adjuntamos el recibo <b>'.e($p['receipt_number']).'</b> correspondiente al proyecto '.e($p['project_number']).'.</p><p><a href="'.e($url).'">Ver, imprimir o guardar el recibo</a></p>';$headers="MIME-Version: 1.0\r\nContent-type: text/html; charset=UTF-8\r\nFrom: ".($cfg['company_email']??'')."\r\n";if(!mail($p['email'],$subject,$html,$headers))throw new Exception('El servidor no pudo enviar el email. Revisá la cuenta de correo de Ferozo.');$db->prepare('UPDATE payments SET email_sent_at=NOW() WHERE id=?')->execute([$id]);msg('Recibo enviado a '.$p['email'].'.');go('?a=project&id='.$p['project_id']);}
 if($a==='save_user'){csrf();if(strlen($_POST['password'])<8)throw new Exception('Clave demasiado corta.');$db->prepare('INSERT INTO users(name,email,password_hash,role) VALUES(?,?,?,?)')->execute([trim($_POST['name']),strtolower(trim($_POST['email'])),password_hash($_POST['password'],PASSWORD_DEFAULT),$_POST['role']]);msg('Usuario creado.');go('?a=users');}
}catch(Throwable $e){if($db->inTransaction())$db->rollBack();msg('No se pudo guardar: '.$e->getMessage());go($_SERVER['HTTP_REFERER']??'index.php');}
if($a==='receipt'){$s=$db->prepare('SELECT p.*,pr.project_number,pr.name project_name,c.business_name,c.cuit FROM payments p JOIN projects pr ON pr.id=p.project_id JOIN clients c ON c.id=pr.client_id WHERE p.id=?');$s->execute([(int)$_GET['id']]);$rp=$s->fetch();if(!$rp){http_response_code(404);exit('Recibo inexistente.');}receipt($db,$cfg,$rp);}
if($a==='receipt_whatsapp'){$s=$db->prepare('SELECT p.*,pr.project_number,c.whatsapp FROM payments p JOIN projects pr ON pr.id=p.project_id JOIN clients c ON c.id=pr.client_id WHERE p.id=?');$s->execute([(int)$_GET['id']]);$rp=$s->fetch();if(!$rp||!$rp['whatsapp']){msg('El cliente no tiene WhatsApp cargado.');go('?a=project&id='.($rp['project_id']??0));}$db->prepare('UPDATE payments SET whatsapp_opened_at=NOW() WHERE id=?')->execute([$rp['id']]);$phone=preg_replace('/\D+/','',$rp['whatsapp']);$url=rtrim($cfg['base_url'],'/').'/?a=public_receipt&token='.$rp['public_token'];$text='Hola, te enviamos el recibo '.$rp['receipt_number'].' correspondiente al proyecto '.$rp['project_number'].': '.$url;header('Location: https://wa.me/'.$phone.'?text='.rawurlencode($text));exit;}
top(ucfirst($a));
if($a==='dashboard'){$summary=['ARS'=>['cargos'=>0.0,'pagos'=>0.0],'USD'=>['cargos'=>0.0,'pagos'=>0.0]];$sumRows=$db->query("SELECT currency,SUM(cargos)cargos,SUM(pagos)pagos FROM (SELECT currency,SUM(amount)cargos,0 pagos FROM charges WHERE active=1 GROUP BY currency UNION ALL SELECT currency,0 cargos,SUM(amount)pagos FROM payments GROUP BY currency) totals GROUP BY currency")->fetchAll();foreach($sumRows as $sum)$summary[$sum['currency']]=['cargos'=>(float)$sum['cargos'],'pagos'=>(float)$sum['pagos']];$rows=$db->query("SELECT p.*,c.business_name,(SELECT COALESCE(SUM(amount),0) FROM charges WHERE project_id=p.id AND active=1 AND currency='ARS') ars_cargos,(SELECT COALESCE(SUM(amount),0) FROM payments WHERE project_id=p.id AND currency='ARS') ars_pagos,(SELECT COALESCE(SUM(amount),0) FROM charges WHERE project_id=p.id AND active=1 AND currency='USD') usd_cargos,(SELECT COALESCE(SUM(amount),0) FROM payments WHERE project_id=p.id AND currency='USD') usd_pagos FROM projects p JOIN clients c ON c.id=p.client_id ORDER BY p.created_at DESC LIMIT 15")->fetchAll();?>
<div class="actions"><h1 style="flex:1">Panel general</h1><?php if(isAdmin()):?><a class="btn" href="?a=new_project">+ Proyecto</a><?php endif;?></div><div class="grid"><div class="card c4"><span class="muted">Cargos vigentes</span><?php foreach(['ARS','USD'] as $cur):?><div class="kpi"><?=mon($summary[$cur]['cargos'],$cur)?></div><?php endforeach;?></div><div class="card c4"><span class="muted">Pagos recibidos</span><?php foreach(['ARS','USD'] as $cur):?><div class="kpi ok"><?=mon($summary[$cur]['pagos'],$cur)?></div><?php endforeach;?></div><div class="card c4"><span class="muted">Saldo total</span><?php foreach(['ARS','USD'] as $cur):?><div class="kpi bad"><?=mon($summary[$cur]['cargos']-$summary[$cur]['pagos'],$cur)?></div><?php endforeach;?></div></div>
<div class="card scroll"><h2>Proyectos</h2><table><tr><th>Proyecto</th><th>Cliente</th><th>Estado</th><th class="right">Saldo ARS</th><th class="right">Saldo USD</th></tr><?php foreach($rows as $r):?><tr><td><a href="?a=project&id=<?=$r['id']?>"><b><?=e($r['project_number'])?></b> · <?=e($r['name'])?></a></td><td><?=e($r['business_name'])?></td><td><span class="pill"><?=e($r['status'])?></span></td><td class="right"><b><?=mon($r['ars_cargos']-$r['ars_pagos'],'ARS')?></b></td><td class="right"><b><?=mon($r['usd_cargos']-$r['usd_pagos'],'USD')?></b></td></tr><?php endforeach;?></table></div>
<?php }elseif($a==='clients'){$rows=$db->query("SELECT c.*,COUNT(p.id) projects,GROUP_CONCAT(CONCAT(p.id,'::',p.project_number,' · ',p.name) ORDER BY p.created_at DESC SEPARATOR '||') project_list FROM clients c LEFT JOIN projects p ON p.client_id=c.id GROUP BY c.id ORDER BY c.business_name")->fetchAll();$ivaLabels=['responsable_inscripto'=>'Responsable inscripto','monotributista'=>'Monotributista','exento'=>'Exento','consumidor_final'=>'Consumidor final','no_responsable'=>'No responsable'];?>
<div class="actions"><h1 style="flex:1">Clientes</h1><?php if(isAdmin()):?><a class="btn" href="?a=new_client">+ Cliente</a><?php endif;?></div><div class="card scroll"><table><tr><th>Cliente</th><th>Contacto</th><th>Datos fiscales</th><th>Ubicación</th><th>Proyectos</th><th>Acciones</th></tr><?php foreach($rows as $r):?><tr style="<?=$r['active']?'':'opacity:.55'?>"><td><b><?=e($r['business_name'])?></b><?php if(!$r['active']):?><br><span class="pill">Inactivo</span><?php endif;?></td><td><?=e($r['contact_name'])?><br><span class="muted"><?=e($r['email'])?><?php if($r['whatsapp']):?> · WhatsApp <?=e($r['whatsapp'])?><?php endif;?></span></td><td><?=e($r['cuit'])?><br><span class="muted"><?=e($ivaLabels[$r['iva_condition']]??$r['iva_condition'])?></span></td><td><?=e($r['city'])?><?php if($r['province']):?>, <?=e($r['province'])?><?php endif;?><br><span class="muted"><?=e($r['country'])?></span></td><td><?php if(!$r['projects']):?>—<?php else:foreach(explode('||',(string)$r['project_list']) as $project):[$projectId,$projectName]=explode('::',$project,2);?><a href="?a=project&id=<?=e($projectId)?>"><?=e($projectName)?></a><br><?php endforeach;endif;?></td><td><?php if(isAdmin()):?><a class="btn light" href="?a=edit_client&id=<?=$r['id']?>">Editar</a><?php endif;?></td></tr><?php endforeach;?></table></div>
<?php }elseif($a==='new_client'){?><div class="card"><h1>Nuevo cliente</h1><form method="post" action="?a=save_client"><?=token()?><div class="grid"><p class="c6"><label>Nombre del cliente o razón social</label><input name="business_name" required></p>
<p class="c6"><label>Persona de contacto (opcional)</label><input name="contact_name"></p>
<p class="c4"><label>CUIT</label><input name="cuit"></p>
<p class="c4"><label>Email</label><input type="email" name="email"></p>
<p class="c4"><label>WhatsApp (con código de país)</label><input name="whatsapp" placeholder="549341..."></p>
<p class="c6"><label>Condición frente al IVA</label><select name="iva_condition" required><option value="">Seleccionar…</option><option value="responsable_inscripto">Responsable inscripto</option><option value="monotributista">Monotributista</option><option value="exento">Exento</option><option value="consumidor_final">Consumidor final</option><option value="no_responsable">No responsable</option></select></p>
<p class="c6"><label>Domicilio</label><input name="address"></p>
<p class="c4"><label>Ciudad</label><input name="city"></p>
<p class="c4"><label>Provincia</label><input name="province"></p>
<p class="c4"><label>País</label><input name="country" value="Argentina"></p>
<p class="c12"><label>Notas</label><textarea name="notes"></textarea></p></div><button class="btn">Guardar</button></form></div>
<?php }elseif($a==='edit_client'){$id=(int)($_GET['id']??0);$s=$db->prepare('SELECT * FROM clients WHERE id=?');$s->execute([$id]);$client=$s->fetch();if(!$client){echo 'Cliente inexistente.';}else{?><div class="card"><div class="actions"><h1 style="flex:1">Editar cliente</h1><a class="btn light" href="?a=clients">Cancelar</a></div><form method="post" action="?a=update_client"><?=token()?><input type="hidden" name="client_id" value="<?=$id?>"><div class="grid"><p class="c6"><label>Nombre del cliente o razón social</label><input name="business_name" value="<?=e($client['business_name'])?>" required></p><p class="c6"><label>Persona de contacto (opcional)</label><input name="contact_name" value="<?=e($client['contact_name'])?>"></p><p class="c4"><label>CUIT</label><input name="cuit" value="<?=e($client['cuit'])?>"></p><p class="c4"><label>Email</label><input type="email" name="email" value="<?=e($client['email'])?>"></p><p class="c4"><label>WhatsApp (con código de país)</label><input name="whatsapp" value="<?=e($client['whatsapp'])?>" placeholder="549341..."></p><p class="c6"><label>Condición frente al IVA</label><select name="iva_condition" required><?php foreach(['responsable_inscripto'=>'Responsable inscripto','monotributista'=>'Monotributista','exento'=>'Exento','consumidor_final'=>'Consumidor final','no_responsable'=>'No responsable'] as $value=>$label):?><option value="<?=$value?>" <?=$client['iva_condition']===$value?'selected':''?>><?=$label?></option><?php endforeach;?></select></p><p class="c6"><label>Domicilio</label><input name="address" value="<?=e($client['address'])?>"></p><p class="c4"><label>Ciudad</label><input name="city" value="<?=e($client['city'])?>"></p><p class="c4"><label>Provincia</label><input name="province" value="<?=e($client['province'])?>"></p><p class="c4"><label>País</label><input name="country" value="<?=e($client['country'])?>"></p><p class="c12"><label>Notas</label><textarea name="notes"><?=e($client['notes'])?></textarea></p><p class="c12"><label><input style="width:auto" type="checkbox" name="active" value="1" <?=$client['active']?'checked':''?>> Cliente activo</label><span class="muted">Los clientes inactivos conservan sus proyectos, pero no aparecen al crear proyectos nuevos.</span></p></div><button class="btn">Guardar cambios</button></form></div><?php }}?>
<?php if($a==='partners'){$rows=$db->query("SELECT pp.*,COUNT(p.id) projects FROM project_partners pp LEFT JOIN projects p ON p.partner_id=pp.id GROUP BY pp.id ORDER BY pp.business_name")->fetchAll();$typeLabels=['arquitecto'=>'Arquitecto/a','estudio_arquitectura'=>'Estudio de arquitectura','constructora'=>'Constructora','desarrolladora'=>'Desarrolladora','otro'=>'Otro'];?>
<div class="actions"><div style="flex:1"><h1>Arquitectos y constructoras</h1><p class="muted">Profesionales y empresas que pueden vincularse opcionalmente a los proyectos.</p></div><?php if(isAdmin()):?><a class="btn" href="?a=new_partner">+ Agregar</a><?php endif;?></div><div class="card scroll"><table><tr><th>Tipo</th><th>Nombre / razón social</th><th>Contacto</th><th>Ubicación</th><th>Proyectos</th></tr><?php foreach($rows as $r):?><tr><td><span class="pill"><?=e($typeLabels[$r['partner_type']]??$r['partner_type'])?></span></td><td><b><?=e($r['business_name'])?></b><br><span class="muted"><?=e($r['cuit'])?></span></td><td><?=e($r['contact_name'])?><br><span class="muted"><?=e($r['email'])?><?php if($r['whatsapp']):?> · WhatsApp <?=e($r['whatsapp'])?><?php endif;?></span></td><td><?=e($r['city'])?><?php if($r['province']):?>, <?=e($r['province'])?><?php endif;?><br><span class="muted"><?=e($r['country'])?></span></td><td><?=$r['projects']?> proyecto<?=$r['projects']==1?'':'s'?></td></tr><?php endforeach;?></table><?php if(!$rows):?><p class="muted">Todavía no cargaste arquitectos, estudios o constructoras.</p><?php endif;?></div>
<?php }elseif($a==='new_partner'){?><div class="card"><h1>Nuevo arquitecto o constructora</h1><form method="post" action="?a=save_partner"><?=token()?><div class="grid"><p class="c4"><label>Tipo</label><select name="partner_type" required><option value="arquitecto">Arquitecto/a</option><option value="estudio_arquitectura">Estudio de arquitectura</option><option value="constructora">Constructora</option><option value="desarrolladora">Desarrolladora</option><option value="otro">Otro</option></select></p><p class="c8"><label>Nombre o razón social</label><input name="business_name" required></p><p class="c6"><label>Persona de contacto (opcional)</label><input name="contact_name"></p><p class="c3"><label>CUIT</label><input name="cuit"></p><p class="c3"><label>WhatsApp</label><input name="whatsapp" placeholder="549341..."></p><p class="c6"><label>Email</label><input type="email" name="email"></p><p class="c6"><label>Domicilio</label><input name="address"></p><p class="c4"><label>Ciudad</label><input name="city"></p><p class="c4"><label>Provincia</label><input name="province"></p><p class="c4"><label>País</label><input name="country" value="Argentina"></p><p class="c12"><label>Notas</label><textarea name="notes"></textarea></p></div><button class="btn">Guardar</button></form></div>
<?php }elseif($a==='projects'){$rows=$db->query('SELECT p.*,c.business_name,pp.business_name partner_name,pp.partner_type FROM projects p JOIN clients c ON c.id=p.client_id LEFT JOIN project_partners pp ON pp.id=p.partner_id ORDER BY p.created_at DESC')->fetchAll();?>
<div class="actions"><h1 style="flex:1">Proyectos</h1><?php if(isAdmin()):?><a class="btn" href="?a=new_project">+ Proyecto</a><?php endif;?></div><div class="card scroll"><table><tr><th>Número</th><th>Nombre</th><th>Cliente</th><th>Arquitecto / constructora</th><th>Estado</th></tr><?php foreach($rows as $r):?><tr><td><a href="?a=project&id=<?=$r['id']?>"><b><?=e($r['project_number'])?></b></a></td><td><?=e($r['name'])?></td><td><?=e($r['business_name'])?></td><td><?=e($r['partner_name']?:'—')?></td><td><span class="pill"><?=e($r['status'])?></span></td></tr><?php endforeach;?></table></div>
<?php }elseif($a==='receipts'){$rows=$db->query('SELECT pa.*,pr.project_number,pr.name project_name,c.business_name,c.email,c.whatsapp,COALESCE((SELECT SUM(a.amount) FROM allocations a WHERE a.payment_id=pa.id),0) allocated FROM payments pa JOIN projects pr ON pr.id=pa.project_id JOIN clients c ON c.id=pr.client_id ORDER BY pa.payment_date DESC,pa.id DESC')->fetchAll();?>
<div class="actions"><div style="flex:1"><h1>Recibos de pago</h1><p class="muted">Cada pago registrado genera automáticamente un recibo y descuenta el saldo del proyecto según su imputación.</p></div></div><div class="card scroll"><table><tr><th>Recibo / fecha</th><th>Cliente</th><th>Proyecto</th><th>Moneda</th><th class="right">Pago</th><th class="right">Imputado</th><th>Acciones</th></tr><?php foreach($rows as $r):?><tr><td><b><?=e($r['receipt_number'])?></b><br><?=e($r['payment_date'])?></td><td><?=e($r['business_name'])?></td><td><a href="?a=project&id=<?=$r['project_id']?>"><?=e($r['project_number'])?> · <?=e($r['project_name'])?></a></td><td><span class="pill"><?=e($r['currency'])?></span></td><td class="right"><b><?=mon($r['amount'],$r['currency'])?></b></td><td class="right"><?=mon($r['allocated'],$r['currency'])?></td><td><div class="actions"><a class="btn light" target="_blank" href="?a=receipt&id=<?=$r['id']?>">Ver / imprimir</a><?php if(isAdmin()&&$r['email']):?><form method="post" action="?a=send_receipt_email"><?=token()?><input type="hidden" name="payment_id" value="<?=$r['id']?>"><button class="btn light">Email</button></form><?php endif;?><?php if($r['whatsapp']):?><a class="btn light" target="_blank" href="?a=receipt_whatsapp&id=<?=$r['id']?>">WhatsApp</a><?php endif;?></div></td></tr><?php endforeach;?></table><?php if(!$rows):?><p class="muted">Todavía no hay recibos. Se crearán al registrar pagos desde cada proyecto.</p><?php endif;?></div>
<?php }elseif($a==='new_project'){$clients=$db->query('SELECT id,business_name FROM clients WHERE active=1 ORDER BY business_name')->fetchAll();$partners=$db->query('SELECT id,business_name,partner_type FROM project_partners WHERE active=1 ORDER BY business_name')->fetchAll();?><div class="card"><h1>Nuevo proyecto</h1><?php if(!$clients):?><p>Primero <a href="?a=new_client">creá un cliente</a>.</p><?php else:?><form method="post" action="?a=save_project"><?=token()?><div class="grid"><p class="c6"><label>Cliente</label><select name="client_id"><?php foreach($clients as $c):?><option value="<?=$c['id']?>"><?=e($c['business_name'])?></option><?php endforeach;?></select></p><p class="c6"><label>Arquitecto, estudio o constructora (opcional)</label><select name="partner_id"><option value="">Sin asignar</option><?php foreach($partners as $partner):?><option value="<?=$partner['id']?>"><?=e($partner['business_name'])?> · <?=e(str_replace('_',' ',$partner['partner_type']))?></option><?php endforeach;?></select></p>
<p class="c3"><label>N.º de proyecto</label><input name="project_number" placeholder="PD-2026-001" required></p>
<p class="c3"><label>Estado</label><select name="status"><option value="consulta">Consulta</option><option value="presupuestado">Presupuestado</option></select></p>
<p class="c6"><label>Nombre del proyecto u obra</label><input name="name" required></p>
<p class="c12"><label>Notas</label><textarea name="notes"></textarea></p></div><button class="btn">Crear proyecto</button></form><?php endif;?></div>
<?php }elseif($a==='edit_project'){$id=(int)$_GET['id'];$s=$db->prepare('SELECT * FROM projects WHERE id=?');$s->execute([$id]);$p=$s->fetch();$clients=$db->query('SELECT id,business_name FROM clients WHERE active=1 ORDER BY business_name')->fetchAll();$partners=$db->query('SELECT id,business_name,partner_type FROM project_partners WHERE active=1 ORDER BY business_name')->fetchAll();if(!$p){echo 'Proyecto inexistente.';}else{?>
<div class="card"><div class="actions"><div style="flex:1"><h1>Editar proyecto</h1><p class="muted"><?=e($p['project_number'])?> · La moneda, el IVA y los importes se editan desde cada presupuesto.</p></div><a class="btn light" href="?a=project&id=<?=$id?>">Cancelar</a></div><form method="post" action="?a=update_project"><?=token()?><input type="hidden" name="project_id" value="<?=$id?>"><div class="grid"><p class="c6"><label>Cliente</label><select name="client_id"><?php foreach($clients as $c):?><option value="<?=$c['id']?>" <?=$c['id']==$p['client_id']?'selected':''?>><?=e($c['business_name'])?></option><?php endforeach;?></select></p><p class="c6"><label>Arquitecto, estudio o constructora (opcional)</label><select name="partner_id"><option value="">Sin asignar</option><?php foreach($partners as $partner):?><option value="<?=$partner['id']?>" <?=$partner['id']==$p['partner_id']?'selected':''?>><?=e($partner['business_name'])?> · <?=e(str_replace('_',' ',$partner['partner_type']))?></option><?php endforeach;?></select></p><p class="c3"><label>N.º de proyecto</label><input name="project_number" value="<?=e($p['project_number'])?>" required></p><p class="c3"><label>Estado</label><select name="status"><?php foreach(['consulta'=>'Consulta','presupuestado'=>'Presupuestado','aprobado'=>'Aprobado','en_obra'=>'En obra','finalizado'=>'Finalizado','cancelado'=>'Cancelado'] as $value=>$label):?><option value="<?=$value?>" <?=$value===$p['status']?'selected':''?>><?=$label?></option><?php endforeach;?></select></p><p class="c6"><label>Nombre del proyecto u obra</label><input name="name" value="<?=e($p['name'])?>" required></p><p class="c12"><label>Notas</label><textarea name="notes"><?=e($p['notes'])?></textarea></p></div><button class="btn">Guardar cambios</button></form></div>
<?php }}elseif($a==='project'){$id=(int)$_GET['id'];$s=$db->prepare('SELECT p.*,c.business_name,pp.business_name partner_name,pp.partner_type FROM projects p JOIN clients c ON c.id=p.client_id LEFT JOIN project_partners pp ON pp.id=p.partner_id WHERE p.id=?');$s->execute([$id]);$p=$s->fetch();if(!$p){echo 'Proyecto inexistente.';}else{$s=$db->prepare('SELECT * FROM quotes WHERE project_id=? ORDER BY version_no DESC');$s->execute([$id]);$quotes=$s->fetchAll();$s=$db->prepare('SELECT c.*,COALESCE(SUM(a.amount),0) paid FROM charges c LEFT JOIN allocations a ON a.charge_id=c.id WHERE c.project_id=? GROUP BY c.id ORDER BY c.currency,c.charge_date,c.id');$s->execute([$id]);$charges=$s->fetchAll();$s=$db->prepare('SELECT p.*,cl.email,cl.whatsapp,COALESCE((SELECT SUM(a.amount) FROM allocations a WHERE a.payment_id=p.id),0) allocated FROM payments p JOIN projects pr ON pr.id=p.project_id JOIN clients cl ON cl.id=pr.client_id WHERE p.project_id=? ORDER BY p.payment_date DESC');$s->execute([$id]);$payments=$s->fetchAll();$totals=[];foreach(['ARS','USD'] as $cur)$totals[$cur]=['total'=>0.0,'paid'=>0.0,'materials'=>0.0,'materials_paid'=>0.0,'labor'=>0.0,'labor_paid'=>0.0];foreach($charges as $charge){if(!$charge['active'])continue;$cur=$charge['currency'];$totals[$cur]['total']+=(float)$charge['amount'];if($charge['type']==='materiales'){$totals[$cur]['materials']+=(float)$charge['amount'];$totals[$cur]['materials_paid']+=(float)$charge['paid'];}elseif(in_array($charge['type'],['ingenieria','mano_obra'],true)){$totals[$cur]['labor']+=(float)$charge['amount'];$totals[$cur]['labor_paid']+=(float)$charge['paid'];}}foreach($payments as $payment)$totals[$payment['currency']]['paid']+=(float)$payment['amount'];?>
<div class="actions"><div style="flex:1"><span class="muted"><?=e($p['business_name'])?><?php if($p['partner_name']):?> · <?=e($p['partner_name'])?><?php endif;?></span><h1><?=e($p['project_number'])?> · <?=e($p['name'])?></h1></div><?php if(isAdmin()):?><a class="btn light" href="?a=edit_project&id=<?=$id?>">Editar proyecto</a><?php endif;?><span class="pill"><?=e($p['status'])?></span></div><?php foreach(['ARS','USD'] as $cur):if($totals[$cur]['total']<.009&&$totals[$cur]['paid']<.009)continue;?><h2><?=e($cur)?></h2><div class="grid"><div class="card c4"><span class="muted">Total vigente</span><div class="kpi"><?=mon($totals[$cur]['total'],$cur)?></div></div><div class="card c4"><span class="muted">Pagado</span><div class="kpi ok"><?=mon($totals[$cur]['paid'],$cur)?></div></div><div class="card c4"><span class="muted">Saldo</span><div class="kpi bad"><?=mon($totals[$cur]['total']-$totals[$cur]['paid'],$cur)?></div></div></div><div class="grid"><div class="card c6"><h3>Materiales</h3><p>Total: <b><?=mon($totals[$cur]['materials'],$cur)?></b> · Imputado: <span class="ok"><?=mon($totals[$cur]['materials_paid'],$cur)?></span></p></div><div class="card c6"><h3>Mano de obra e ingeniería</h3><p>Total: <b><?=mon($totals[$cur]['labor'],$cur)?></b> · Imputado: <span class="ok"><?=mon($totals[$cur]['labor_paid'],$cur)?></span></p></div></div><?php endforeach;?>
<div class="card"><div class="actions"><h2 style="flex:1">Presupuestos por rubro</h2><?php if(isAdmin()):?><a class="btn light" href="?a=new_quote&project_id=<?=$id?>">+ Agregar presupuesto</a><?php endif;?></div><p class="muted">Podés cargar por separado Domótica, Redes, Cámaras, Alarma y Audio. Cada presupuesto conserva su moneda, PDF, IVA, Materiales y Mano de obra.</p><div class="scroll"><table><tr><th>Rubro</th><th>Versión</th><th>Fecha</th><th>Estado</th><th>Moneda</th><th class="right">Materiales</th><th class="right">Mano de obra</th><th>IVA</th><th class="right">Total</th><th>Archivo</th></tr><?php $categoryLabels=['general'=>'General / anterior','domotica'=>'Domótica','redes'=>'Redes','camaras'=>'Cámaras','alarma'=>'Alarma','audio'=>'Audio'];$taxLabels=['sin_iva'=>'Sin IVA','iva_incluido'=>'IVA incluido','mas_iva'=>'Más IVA'];foreach($quotes as $r):?><tr><td><span class="pill"><?=e($categoryLabels[$r['quote_category']]??$r['quote_category'])?></span></td><td>v<?=$r['version_no']?></td><td><?=e($r['quote_date'])?></td><td><span class="pill"><?=e($r['status'])?></span></td><td><span class="pill"><?=e($r['currency'])?></span></td><td class="right"><?=mon($r['materials_amount'],$r['currency'])?></td><td class="right"><?=mon($r['labor_amount'],$r['currency'])?></td><td><?=e($taxLabels[$r['tax_mode']]??$r['tax_mode'])?></td><td class="right"><b><?=mon($r['total'],$r['currency'])?></b></td><td><?=$r['file_path']?'<a target="_blank" href="'.e($r['file_path']).'">Ver PDF</a>':'—'?></td></tr><?php endforeach;?></table></div></div>
<div class="card"><div class="actions"><h2 style="flex:1">Cargos</h2><?php if(isAdmin()):?><a class="btn light" href="?a=new_charge&project_id=<?=$id?>">+ Cargo</a><?php endif;?></div><div class="scroll"><table><tr><th>Fecha</th><th>Concepto</th><th>Moneda</th><th class="right">Importe</th><th class="right">Imputado</th><th class="right">Pendiente</th></tr><?php foreach($charges as $r):?><tr style="<?=$r['active']?'':'opacity:.45'?>"><td><?=e($r['charge_date'])?></td><td><span class="pill"><?=e($r['type'])?></span> <?=e($r['description'])?> <?=$r['active']?'':'(absorbido)'?></td><td><?=e($r['currency'])?></td><td class="right"><?=mon($r['amount'],$r['currency'])?></td><td class="right"><?=mon($r['paid'],$r['currency'])?></td><td class="right"><b><?=mon($r['active']?$r['amount']-$r['paid']:0,$r['currency'])?></b></td></tr><?php endforeach;?></table></div></div>
<div class="card"><div class="actions"><h2 style="flex:1">Pagos y recibos</h2><?php if(isAdmin()):?><a class="btn" href="?a=new_payment&project_id=<?=$id?>">+ Registrar pago y generar recibo</a><?php endif;?></div><div class="scroll"><table><tr><th>Fecha / recibo</th><th>Medio</th><th>Moneda</th><th class="right">Pago</th><th class="right">Imputado</th><th>Acciones</th></tr><?php foreach($payments as $r):?><tr><td><?=e($r['payment_date'])?><br><b><?=e($r['receipt_number'])?></b></td><td><?=e($r['method'])?> · <?=e($r['reference'])?></td><td><?=e($r['currency'])?></td><td class="right"><b><?=mon($r['amount'],$r['currency'])?></b></td><td class="right"><?=mon($r['allocated'],$r['currency'])?></td><td><div class="actions"><a class="btn light" target="_blank" href="?a=receipt&id=<?=$r['id']?>">Ver recibo</a><?php if(isAdmin()&&$r['email']):?><form method="post" action="?a=send_receipt_email"><?=token()?><input type="hidden" name="payment_id" value="<?=$r['id']?>"><button class="btn light">Email</button></form><?php endif;?><?php if($r['whatsapp']):?><a class="btn light" target="_blank" href="?a=receipt_whatsapp&id=<?=$r['id']?>">WhatsApp</a><?php endif;?></div><?php if($r['email_sent_at']):?><small class="muted">Email: <?=e($r['email_sent_at'])?></small><?php endif;?><?php if($r['whatsapp_opened_at']):?><small class="muted"> · WhatsApp: <?=e($r['whatsapp_opened_at'])?></small><?php endif;?></td></tr><?php endforeach;?></table></div></div>
<?php }}elseif($a==='new_quote'){$pid=(int)$_GET['project_id'];$s=$db->prepare('SELECT p.*,COALESCE(MAX(q.version_no),0)+1 nextv FROM projects p LEFT JOIN quotes q ON q.project_id=p.id WHERE p.id=? GROUP BY p.id');$s->execute([$pid]);$p=$s->fetch();?><div class="card"><h1>Agregar presupuesto</h1><p class="muted"><?=e($p['project_number']??'')?> · Elegí el rubro, la moneda y la condición de IVA de este presupuesto.</p><form method="post" action="?a=save_quote" enctype="multipart/form-data"><?=token()?><input type="hidden" name="project_id" value="<?=$pid?>"><div class="grid"><p class="c4"><label>Rubro del presupuesto</label><select name="quote_category" required><option value="">Seleccionar…</option><option value="domotica">Domótica</option><option value="redes">Redes</option><option value="camaras">Cámaras</option><option value="alarma">Alarma</option><option value="audio">Audio</option></select></p><p class="c2"><label>Versión</label><input type="number" name="version_no" value="<?=$p['nextv']?>" required></p><p class="c3"><label>Moneda</label><select name="currency" required><option value="ARS">Pesos argentinos ($)</option><option value="USD">Dólares estadounidenses (US$)</option></select></p>
<p class="c3"><label>Fecha</label><input type="date" name="quote_date" value="<?=date('Y-m-d')?>" required></p>
<p class="c3"><label>Materiales</label><input type="number" step=".01" min="0" name="materials_amount" required></p>
<p class="c3"><label>Mano de obra</label><input type="number" step=".01" min="0" name="labor_amount" required></p>
<p class="c3"><label>Estado</label><select name="status"><option value="borrador">Borrador</option><option value="enviado">Enviado</option><option value="aprobado_inicial">Aprobado inicial (crea 10%)</option><option value="final">Final (crea obra)</option><option value="rechazado">Rechazado</option></select></p>
<p class="c4"><label>IVA</label><select name="tax_mode"><option value="sin_iva">Sin IVA</option><option value="iva_incluido">IVA incluido</option><option value="mas_iva">Más IVA</option></select></p>
<p class="c4"><label>Alícuota %</label><input type="number" step=".01" name="vat_rate" value="<?=e($p['vat_rate'])?>"></p>
<p class="c4"><label>Adelanto de ingeniería %</label><input type="number" min="0" max="100" step=".01" name="engineering_pct" value="10" required></p>
<p class="c4"><label>Presupuesto en PDF</label><input type="file" name="quote_file" accept=".pdf,application/pdf" required></p>
<p class="c12"><label>Cambios / notas</label><textarea name="notes"></textarea></p></div><button class="btn">Guardar presupuesto</button></form></div>
<?php }elseif($a==='new_charge'){$pid=(int)$_GET['project_id'];?><div class="card"><h1>Nuevo cargo</h1><form method="post" action="?a=save_charge"><?=token()?><input type="hidden" name="project_id" value="<?=$pid?>"><div class="grid"><p class="c3"><label>Fecha</label><input type="date" name="charge_date" value="<?=date('Y-m-d')?>" required></p><p class="c3"><label>Moneda</label><select name="currency" required><option value="ARS">ARS</option><option value="USD">USD</option></select></p>
<p class="c3"><label>Tipo</label><select name="type"><option value="adicional">Adicional</option><option value="materiales">Materiales</option><option value="mano_obra">Mano de obra</option><option value="ingenieria">Ingeniería</option><option value="ajuste">Ajuste</option></select></p>
<p class="c3"><label>Importe</label><input type="number" min="0" step=".01" name="amount" required></p>
<p class="c12"><label>Descripción</label><input name="description" required></p></div><button class="btn">Agregar</button></form></div>
<?php }elseif($a==='new_payment'){$pid=(int)$_GET['project_id'];$s=$db->prepare('SELECT project_number,name FROM projects WHERE id=?');$s->execute([$pid]);$paymentProject=$s->fetch();$s=$db->prepare('SELECT c.*,COALESCE(SUM(a.amount),0) paid FROM charges c LEFT JOIN allocations a ON a.charge_id=c.id WHERE c.project_id=? AND c.active=1 GROUP BY c.id HAVING c.amount-paid>0.009');$s->execute([$pid]);$charges=$s->fetchAll();?><div class="card"><h1>Registrar pago y generar recibo</h1><p class="muted"><?=e($paymentProject['project_number']??'')?> · <?=e($paymentProject['name']??'')?>. Elegí la moneda del pago; solo podrá imputarse a cargos de esa misma moneda.</p><form method="post" action="?a=save_payment" enctype="multipart/form-data"><?=token()?><input type="hidden" name="project_id" value="<?=$pid?>"><div class="grid"><p class="c3"><label>Fecha</label><input type="date" name="payment_date" value="<?=date('Y-m-d')?>" required></p><p class="c3"><label>Moneda</label><select name="currency" id="payment-currency" required onchange="filterCharges()"><option value="ARS">Pesos argentinos ($)</option><option value="USD">Dólares estadounidenses (US$)</option></select></p>
<p class="c3"><label>Importe</label><input type="number" min=".01" step=".01" name="amount" required></p>
<p class="c3"><label>Medio</label><select name="method"><option value="transferencia">Transferencia</option><option value="efectivo">Efectivo</option><option value="cheque">Cheque</option><option value="tarjeta">Tarjeta</option><option value="otro">Otro</option></select></p>
<p class="c3"><label>Referencia</label><input name="reference"></p>
<p class="c6"><label>Comprobante</label><input type="file" name="receipt" accept=".pdf,.jpg,.jpeg,.png"></p>
<p class="c12"><label>Notas</label><textarea name="notes"></textarea></p></div><h3>Asignación del pago</h3><p class="muted">Indicá cuánto corresponde a cada concepto de la moneda seleccionada.</p><table><tr><th>Concepto</th><th class="right">Pendiente</th><th>Monto a asignar</th></tr><?php foreach($charges as $c):$due=$c['amount']-$c['paid'];?><tr class="charge-row" data-currency="<?=e($c['currency'])?>"><td><span class="pill"><?=e($c['type'])?></span> <?=e($c['description'])?></td><td class="right"><?=mon($due,$c['currency'])?></td><td style="width:200px"><input class="allocation" type="number" min="0" max="<?=$due?>" step=".01" name="alloc[<?=$c['id']?>]" value="0"></td></tr><?php endforeach;?></table><br><button class="btn">Guardar pago y generar recibo</button></form><script>function filterCharges(){const cur=document.getElementById('payment-currency').value;document.querySelectorAll('.charge-row').forEach(row=>{const show=row.dataset.currency===cur;row.style.display=show?'':'none';if(!show)row.querySelector('.allocation').value=0;});}filterCharges();</script></div>
<?php }elseif($a==='users'&&isAdmin()){$users=$db->query('SELECT * FROM users ORDER BY name')->fetchAll();?><div class="grid"><div class="card c8"><h1>Usuarios</h1><table><tr><th>Nombre</th><th>Email</th><th>Rol</th></tr><?php foreach($users as $u):?><tr><td><?=e($u['name'])?></td><td><?=e($u['email'])?></td><td><?=e($u['role'])?></td></tr><?php endforeach;?></table></div><div class="card c4"><h2>Nuevo usuario</h2><form method="post" action="?a=save_user"><?=token()?><p><label>Nombre</label><input name="name" required></p>
<p><label>Email</label><input type="email" name="email" required></p>
<p><label>Clave</label><input type="password" minlength="8" name="password" required></p>
<p><label>Rol</label><select name="role"><option value="admin">Administrador</option><option value="consulta">Solo consulta</option></select></p><button class="btn">Crear</button></form></div></div><?php }
bottom();
