<?php
declare(strict_types=1);
session_start();
$root=dirname(__DIR__,3);
$cfg=require $root.'/config.php';
date_default_timezone_set($cfg['timezone']??'America/Argentina/Buenos_Aires');
$db=new PDO('mysql:host='.$cfg['db_host'].';dbname='.$cfg['db_name'].';charset=utf8mb4',$cfg['db_user'],$cfg['db_pass'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
if(empty($_SESSION['user'])){header('Location:index.php');exit;}
$_SESSION['csrf']??=bin2hex(random_bytes(24));
require_once $root.'/app/Core/UnifiedSidebar.php';
function ec($v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function gc(string $u):never{header('Location:'.$u);exit;}
function cc():void{if(!hash_equals($_SESSION['csrf']??'',$_POST['csrf']??'')){http_response_code(419);exit('Solicitud vencida.');}}
function cm():bool{if(($_SESSION['user']['role']??'')==='admin')return true;return !empty($_SESSION['user']['permissions']['clients']['manage']);}
function normalizePhone(string $v):string{return preg_replace('/\D+/','',$v)??'';}
function dupClient(PDO $db,string $name,string $cuit,string $email,string $whatsapp,int $exclude=0):?array{
 $tests=[];$params=[];
 if($cuit!==''){$tests[]="REPLACE(REPLACE(REPLACE(cuit,'-',''),'.',''),' ','')=?";$params[]=preg_replace('/\D+/','',$cuit);}
 if($email!==''){$tests[]='LOWER(email)=?';$params[]=strtolower($email);}
 $phone=normalizePhone($whatsapp);if($phone!==''){$tests[]="REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(whatsapp,'+',''),' ',''),'-',''),'(',''),')','')=?";$params[]=$phone;}
 if($name!==''){$tests[]='LOWER(TRIM(business_name))=?';$params[]=strtolower(trim($name));}
 if(!$tests)return null;
 $sql='SELECT id,client_number,business_name,email,whatsapp,cuit FROM clients WHERE ('.implode(' OR ',$tests).')'.($exclude?' AND id<>?':'').' ORDER BY id LIMIT 1';
 if($exclude)$params[]=$exclude;$s=$db->prepare($sql);$s->execute($params);return $s->fetch()?:null;
}
function topc(string $title):void{$m=$_SESSION['msg']??null;unset($_SESSION['msg']);?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=ec($title)?> · Punto ERP</title><style><?=erpSidebarCss()?>body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.45 system-ui}.main{margin-left:var(--sidebar);padding:32px 4%}.card{background:#fff;border:1px solid var(--line);border-radius:14px;padding:22px;margin-bottom:18px}.grid{display:grid;grid-template-columns:repeat(12,1fr);gap:16px}.c3{grid-column:span 3}.c4{grid-column:span 4}.c6{grid-column:span 6}.c12{grid-column:span 12}label{display:block;font-weight:650;margin-bottom:6px}input,select,textarea{width:100%;padding:10px 11px;border:1px solid #cbd1d7;border-radius:8px;background:#fff;font:inherit}input[type=checkbox]{width:auto}.btn{display:inline-block;border:0;border-radius:8px;padding:10px 15px;background:var(--o);color:#fff;text-decoration:none;font-weight:700;cursor:pointer}.btn.light{background:#edf0f3;color:var(--ink)}.danger{color:#b42318!important}.actions{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.muted{color:var(--muted)}.flash{padding:12px 16px;background:#fff0e5;border:1px solid #ffd2b1;border-radius:9px;margin-bottom:18px}.scroll{overflow:auto}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:11px 9px;border-bottom:1px solid var(--line);vertical-align:middle}th{font-size:12px;text-transform:uppercase;color:var(--muted)}th a{color:inherit;text-decoration:none;white-space:nowrap}th a:hover{color:var(--o)}.filters{padding:16px 18px}.filters .grid{align-items:end}.filters p{margin:0}.filter-actions{display:flex;gap:8px;align-items:center;padding-bottom:1px}@media(max-width:900px){.main{margin-left:0;padding:22px}.c3,.c4,.c6{grid-column:span 12}}</style></head><body><?php erpSidebar('clients');?><main class="main"><?php if($m):?><div class="flash"><?=ec($m)?></div><?php endif;?><?php }
function bottomc():void{?></main></body></html><?php }
$a=$_GET['a']??'clients';
try{
 if($a==='save_client'){if(!cm())throw new Exception('No autorizado.');cc();$name=trim((string)($_POST['business_name']??''));$cuit=trim((string)($_POST['cuit']??''));$email=strtolower(trim((string)($_POST['email']??'')));$wa=trim((string)($_POST['whatsapp']??''));if($name==='')throw new Exception('Ingresá el nombre del cliente.');if($email!==''&&!filter_var($email,FILTER_VALIDATE_EMAIL))throw new Exception('Email inválido.');if($d=dupClient($db,$name,$cuit,$email,$wa)){throw new Exception('Ya existe un cliente posiblemente duplicado: '.$d['business_name'].' (N° '.($d['client_number']?:$d['id']).').');}$next=(int)$db->query('SELECT COALESCE(MAX(client_number),0)+1 FROM clients')->fetchColumn();$db->prepare('INSERT INTO clients(client_number,business_name,contact_name,cuit,iva_condition,email,whatsapp,address,city,province,country,notes,active) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,1)')->execute([$next,$name,trim((string)$_POST['contact_name']),$cuit,$_POST['iva_condition']??'consumidor_final',$email,$wa,trim((string)$_POST['address']),trim((string)$_POST['city']),trim((string)$_POST['province']),trim((string)($_POST['country']??'Argentina'))?:'Argentina',trim((string)$_POST['notes'])]);$_SESSION['msg']='Cliente creado.';gc('?a=clients');}
 if($a==='update_client'){if(!cm())throw new Exception('No autorizado.');cc();$id=(int)$_POST['client_id'];$name=trim((string)$_POST['business_name']);$cuit=trim((string)$_POST['cuit']);$email=strtolower(trim((string)$_POST['email']));$wa=trim((string)$_POST['whatsapp']);if($d=dupClient($db,$name,$cuit,$email,$wa,$id)){throw new Exception('Los datos coinciden con otro cliente: '.$d['business_name'].' (N° '.($d['client_number']?:$d['id']).').');}$db->prepare('UPDATE clients SET business_name=?,contact_name=?,cuit=?,iva_condition=?,email=?,whatsapp=?,address=?,city=?,province=?,country=?,notes=?,active=? WHERE id=?')->execute([$name,trim((string)$_POST['contact_name']),$cuit,$_POST['iva_condition']??'consumidor_final',$email,$wa,trim((string)$_POST['address']),trim((string)$_POST['city']),trim((string)$_POST['province']),trim((string)($_POST['country']??'Argentina'))?:'Argentina',trim((string)$_POST['notes']),isset($_POST['active'])?1:0,$id]);$_SESSION['msg']='Cliente actualizado.';gc('?a=clients');}
 if($a==='delete_client'){if(!cm())throw new Exception('No autorizado.');cc();$id=(int)$_POST['client_id'];$s=$db->prepare('SELECT COUNT(*) FROM projects WHERE client_id=?');$s->execute([$id]);if((int)$s->fetchColumn()>0)throw new Exception('No se puede eliminar porque el cliente tiene proyectos asociados. Podés desactivarlo desde Editar.');$db->prepare('DELETE FROM clients WHERE id=?')->execute([$id]);$_SESSION['msg']='Cliente eliminado.';gc('?a=clients');}
}catch(Throwable $e){$_SESSION['msg']='No se pudo completar la acción: '.$e->getMessage();gc($_SERVER['HTTP_REFERER']??'?a=clients');}
if($a==='clients'){
 $q=trim((string)($_GET['q']??''));$city=trim((string)($_GET['city']??''));$status=(string)($_GET['status']??'all');$sort=(string)($_GET['sort']??'name');$dir=strtolower((string)($_GET['dir']??'asc'))==='desc'?'desc':'asc';
 $sortMap=['number'=>'c.client_number','name'=>'c.business_name','contact'=>'c.contact_name','city'=>'c.city','projects'=>'projects','status'=>'c.active'];if(!isset($sortMap[$sort]))$sort='name';
 $where=[];$params=[];if($q!==''){$where[]='(c.business_name LIKE ? OR c.contact_name LIKE ? OR c.cuit LIKE ? OR c.email LIKE ? OR c.whatsapp LIKE ? OR CAST(c.client_number AS CHAR) LIKE ?)';for($i=0;$i<6;$i++)$params[]='%'.$q.'%';}if($city!==''){$where[]='c.city=?';$params[]=$city;}if($status==='active')$where[]='c.active=1';elseif($status==='inactive')$where[]='c.active=0';
 $sql='SELECT c.*,COUNT(p.id) projects FROM clients c LEFT JOIN projects p ON p.client_id=c.id'.($where?' WHERE '.implode(' AND ',$where):'').' GROUP BY c.id ORDER BY '.$sortMap[$sort].' '.strtoupper($dir).',c.business_name ASC';$s=$db->prepare($sql);$s->execute($params);$rows=$s->fetchAll();$cities=$db->query("SELECT DISTINCT city FROM clients WHERE city IS NOT NULL AND TRIM(city)<>'' ORDER BY city")->fetchAll(PDO::FETCH_COLUMN);
 $base=['a'=>'clients','q'=>$q,'city'=>$city,'status'=>$status];$sortUrl=function(string $field)use($base,$sort,$dir):string{$p=$base;$p['sort']=$field;$p['dir']=($sort===$field&&$dir==='asc')?'desc':'asc';return '?'.http_build_query($p);};$arrow=function(string $field)use($sort,$dir):string{return $sort===$field?($dir==='asc'?' ↑':' ↓'):'';};
 topc('Clientes');?><div class="actions"><div style="flex:1"><h1>Clientes</h1><p class="muted">Podés buscar, filtrar y ordenar el listado. Se controla duplicación por CUIT, email, WhatsApp y nombre.</p></div><?php if(cm()):?><a class="btn" href="?a=new_client">+ Cliente</a><?php endif;?></div><form class="card filters" method="get"><input type="hidden" name="a" value="clients"><input type="hidden" name="sort" value="<?=ec($sort)?>"><input type="hidden" name="dir" value="<?=ec($dir)?>"><div class="grid"><p class="c6"><label>Buscar</label><input name="q" value="<?=ec($q)?>" placeholder="Nombre, contacto, CUIT, email, WhatsApp o N° de cliente"></p><p class="c3"><label>Ciudad</label><select name="city"><option value="">Todas</option><?php foreach($cities as $c):?><option value="<?=ec($c)?>" <?=$city===$c?'selected':''?>><?=ec($c)?></option><?php endforeach;?></select></p><p class="c3"><label>Estado</label><select name="status"><option value="all" <?=$status==='all'?'selected':''?>>Todos</option><option value="active" <?=$status==='active'?'selected':''?>>Activos</option><option value="inactive" <?=$status==='inactive'?'selected':''?>>Inactivos</option></select></p><div class="c12 filter-actions"><button class="btn">Aplicar filtros</button><a class="btn light" href="?a=clients">Limpiar</a><span class="muted"><?=count($rows)?> cliente<?=count($rows)===1?'':'s'?></span></div></div></form><div class="card scroll"><table><tr><th><a href="<?=$sortUrl('number')?>">N°<?=$arrow('number')?></a></th><th><a href="<?=$sortUrl('name')?>">Cliente<?=$arrow('name')?></a></th><th><a href="<?=$sortUrl('contact')?>">Contacto<?=$arrow('contact')?></a></th><th><a href="<?=$sortUrl('city')?>">Ubicación<?=$arrow('city')?></a></th><th><a href="<?=$sortUrl('projects')?>">Proyectos<?=$arrow('projects')?></a></th><th><a href="<?=$sortUrl('status')?>">Estado<?=$arrow('status')?></a></th><th>Acciones</th></tr><?php foreach($rows as $r):?><tr style="<?=$r['active']?'':'opacity:.55'?>"><td><?=ec($r['client_number']??$r['id'])?></td><td><b><?=ec($r['business_name'])?></b><br><span class="muted"><?=ec($r['cuit'])?></span></td><td><?=ec($r['contact_name'])?><br><span class="muted"><?=ec($r['email'])?><?=($r['whatsapp']?' · '.ec($r['whatsapp']):'')?></span></td><td><?=ec($r['city'])?><?=($r['province']?', '.ec($r['province']):'')?></td><td><?=ec($r['projects'])?></td><td><?=($r['active']?'Activo':'Inactivo')?></td><td><div class="actions"><?php if(cm()):?><a class="btn light" href="?a=edit_client&id=<?=$r['id']?>">Editar</a><form method="post" action="?a=delete_client" onsubmit="return confirm('¿Eliminar este cliente? Esta acción no se puede deshacer.')"><input type="hidden" name="csrf" value="<?=ec($_SESSION['csrf'])?>"><input type="hidden" name="client_id" value="<?=$r['id']?>"><button class="btn light danger">Eliminar</button></form><?php endif;?></div></td></tr><?php endforeach;?></table></div><?php bottomc();exit;}
if(in_array($a,['new_client','edit_client'],true)){$p=['id'=>0,'business_name'=>'','contact_name'=>'','cuit'=>'','iva_condition'=>'consumidor_final','email'=>'','whatsapp'=>'','address'=>'','city'=>'','province'=>'','country'=>'Argentina','notes'=>'','active'=>1];if($a==='edit_client'){$s=$db->prepare('SELECT * FROM clients WHERE id=?');$s->execute([(int)($_GET['id']??0)]);$p=$s->fetch();if(!$p)exit('Cliente inexistente.');}topc($p['id']?'Editar cliente':'Nuevo cliente');?><div class="card"><div class="actions"><h1 style="flex:1"><?=$p['id']?'Editar cliente':'Nuevo cliente'?></h1><a class="btn light" href="?a=clients">Volver</a></div><form method="post" action="?a=<?=$p['id']?'update_client':'save_client'?>"><input type="hidden" name="csrf" value="<?=ec($_SESSION['csrf'])?>"><?php if($p['id']):?><input type="hidden" name="client_id" value="<?=$p['id']?>"><?php endif;?><div class="grid"><p class="c6"><label>Nombre / razón social</label><input name="business_name" value="<?=ec($p['business_name'])?>" required></p><p class="c6"><label>Persona de contacto</label><input name="contact_name" value="<?=ec($p['contact_name'])?>"></p><p class="c4"><label>CUIT</label><input name="cuit" value="<?=ec($p['cuit'])?>"></p><p class="c4"><label>Email</label><input type="email" name="email" value="<?=ec($p['email'])?>"></p><p class="c4"><label>WhatsApp</label><input name="whatsapp" value="<?=ec($p['whatsapp'])?>"></p><p class="c6"><label>Condición IVA</label><select name="iva_condition"><?php foreach(['responsable_inscripto'=>'Responsable inscripto','monotributista'=>'Monotributista','exento'=>'Exento','consumidor_final'=>'Consumidor final','no_responsable'=>'No responsable'] as $k=>$v):?><option value="<?=$k?>" <?=$p['iva_condition']===$k?'selected':''?>><?=$v?></option><?php endforeach;?></select></p><p class="c6"><label>Dirección</label><input name="address" value="<?=ec($p['address'])?>"></p><p class="c4"><label>Ciudad</label><input name="city" value="<?=ec($p['city'])?>"></p><p class="c4"><label>Provincia</label><input name="province" value="<?=ec($p['province'])?>"></p><p class="c4"><label>País</label><input name="country" value="<?=ec($p['country'])?>"></p><p class="c12"><label>Notas</label><textarea name="notes"><?=ec($p['notes'])?></textarea></p><?php if($p['id']):?><p class="c12"><label style="font-weight:400"><input type="checkbox" name="active" value="1" <?=$p['active']?'checked':''?>> Cliente activo</label></p><?php endif;?></div><button class="btn">Guardar cliente</button></form></div><?php bottomc();exit;}
gc('?a=clients');