<?php
declare(strict_types=1);
session_start();
$root=dirname(__DIR__,3);$cfg=require $root.'/config.php';date_default_timezone_set($cfg['timezone']??'America/Argentina/Buenos_Aires');
$db=new PDO('mysql:host='.$cfg['db_host'].';dbname='.$cfg['db_name'].';charset=utf8mb4',$cfg['db_user'],$cfg['db_pass'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
if(empty($_SESSION['user'])){header('Location:index.php');exit;}
require_once $root.'/app/Core/UnifiedSidebar.php';
function e($v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function usd($n):string{return 'US$ '.number_format((float)$n,2,',','.');}
$quotes=$db->query("SELECT q.*,p.project_number,p.name project_name,c.business_name,(SELECT COUNT(*) FROM quote_items qi WHERE qi.quote_id=q.id) item_count FROM quotes q JOIN projects p ON p.id=q.project_id JOIN clients c ON c.id=p.client_id ORDER BY q.quote_date DESC,q.id DESC")->fetchAll();$msg=$_SESSION['msg']??null;unset($_SESSION['msg']);
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Presupuestos · Punto ERP</title><style><?=erpSidebarCss()?>body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.45 system-ui,-apple-system,Segoe UI,sans-serif}.main{margin-left:var(--sidebar);padding:32px 4%}.card{background:#fff;border:1px solid var(--line);border-radius:14px;padding:22px;margin-bottom:18px}.row{display:flex;justify-content:space-between;gap:16px;align-items:center;flex-wrap:wrap}.btn{display:inline-block;border:0;border-radius:8px;padding:10px 15px;background:var(--o);color:#fff;text-decoration:none;font-weight:700}.btn.gray{background:#edf0f3;color:#27303b}.muted{color:var(--muted)}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:11px 9px;border-bottom:1px solid var(--line)}th{font-size:12px;text-transform:uppercase;color:var(--muted)}.pill{display:inline-block;padding:4px 8px;border-radius:20px;background:#edf0f3;font-size:12px}.flash{padding:12px 15px;background:#fff0e5;border:1px solid #ffd2b1;border-radius:9px;margin-bottom:18px}@media(max-width:900px){.main{margin-left:0;padding:22px 18px}}</style></head><body><?php erpSidebar('quotes');?><main class="main"><?php if($msg):?><div class="flash"><?=e($msg)?></div><?php endif;?><div class="row"><div><h1>Presupuestos</h1><p class="muted">Creá presupuestos seleccionando cliente, proyecto y productos del catálogo.</p></div><a class="btn" href="?a=new_quote">+ Nuevo presupuesto</a></div><div class="card"><div style="overflow:auto"><table><thead><tr><th>Fecha</th><th>Cliente</th><th>Proyecto</th><th>Versión</th><th>Plantilla</th><th>Productos</th><th>Estado</th><th>Total</th><th></th></tr></thead><tbody><?php if(!$quotes):?><tr><td colspan="9" class="muted">Todavía no hay presupuestos.</td></tr><?php endif;?><?php foreach($quotes as $q):$legacy=(int)$q['item_count']===0;?><tr><td><?=e(date('d/m/Y',strtotime($q['quote_date'])))?></td><td><?=e($q['business_name'])?></td><td><?=e($q['project_number'].' · '.$q['project_name'])?></td><td>v<?=e($q['version_no'])?></td><td><?=e($q['quote_template_family']??($q['quote_families']??'—'))?></td><td><?=$legacy?'<span class="pill">Formato anterior</span>':e((string)$q['item_count'])?></td><td><?=e($q['status'])?></td><td><?=usd($q['total'])?></td><td><?php if(!$legacy):?><a class="btn gray" href="?a=quote_view&id=<?=$q['id']?>">Ver</a><?php else:?><a class="btn gray" href="?a=project&id=<?=$q['project_id']?>">Abrir proyecto</a><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></div></main></body></html>