<?php
declare(strict_types=1);
$a=$_GET['a']??'new_quote';$root=dirname(__DIR__,3);
if(in_array($a,['save_quote','update_quote'],true)){
 session_start();$cfg=require $root.'/config.php';date_default_timezone_set($cfg['timezone']??'America/Argentina/Buenos_Aires');$db=new PDO('mysql:host='.$cfg['db_host'].';dbname='.$cfg['db_name'].';charset=utf8mb4',$cfg['db_user'],$cfg['db_pass'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
 if(empty($_SESSION['user'])){header('Location:index.php');exit;}if(($_SESSION['user']['role']??'')!=='admin'){http_response_code(403);exit('No autorizado.');}if(!hash_equals($_SESSION['csrf']??'',$_POST['csrf']??'')){http_response_code(419);exit('Solicitud vencida.');}
 $go=static function(string $u):never{header('Location:'.$u);exit;};$brand=static function(string $cat):string{$x=mb_strtolower($cat);if(str_contains($x,'control4')||str_contains($x,'c4'))return 'Control4';if(str_contains($x,'shelly'))return 'Shelly';if(str_contains($x,'lifesmart')||str_contains($x,'domot'))return 'LifeSmart';return 'Otro';};
 $replaceCharge=static function(PDO $db,int $projectId,int $newChargeId,array $types):void{$m=implode(',',array_fill(0,count($types),'?'));$s=$db->prepare("SELECT id FROM charges WHERE project_id=? AND active=1 AND id<>? AND type IN ($m)");$s->execute(array_merge([$projectId,$newChargeId],$types));foreach($s as $old){$als=$db->prepare('SELECT payment_id,amount FROM allocations WHERE charge_id=?');$als->execute([$old['id']]);foreach($als as $al)$db->prepare('INSERT INTO allocations(payment_id,charge_id,amount) VALUES(?,?,?) ON DUPLICATE KEY UPDATE amount=amount+VALUES(amount)')->execute([$al['payment_id'],$newChargeId,$al['amount']]);$db->prepare('DELETE FROM allocations WHERE charge_id=?')->execute([$old['id']]);$db->prepare('UPDATE charges SET active=0 WHERE id=?')->execute([$old['id']]);}};
 try{
  $qid=(int)($_POST['quote_id']??0);$pid=(int)($_POST['project_id']??0);$clientId=(int)($_POST['client_id']??0);$listId=(int)($_POST['price_list_id']??0);$s=$db->prepare('SELECT p.*,c.id client_id FROM projects p JOIN clients c ON c.id=p.client_id WHERE p.id=? AND c.id=?');$s->execute([$pid,$clientId]);$project=$s->fetch();if(!$project)throw new Exception('Seleccioná un proyecto válido.');
  $families=array_values(array_intersect(['lifesmart','control4','shelly'],$_POST['quote_families']??[]));if(!$families)throw new Exception('Seleccioná al menos una familia.');$template=$_POST['quote_template_family']??'';if(!in_array($template,$families,true))$template=$families[0];
  $s=$db->prepare('SELECT id,name,markup_percentage FROM price_lists WHERE id=? AND active=1');$s->execute([$listId]);$list=$s->fetch();if(!$list)throw new Exception('Seleccioná una lista de precios.');$defaultMarkup=(float)$list['markup_percentage'];$hasOverrides=true;try{$db->query('SELECT 1 FROM product_price_overrides LIMIT 1');}catch(Throwable $e){$hasOverrides=false;}
  $prodQ=$db->prepare("SELECT p.id,p.sku,p.description,p.unit,p.cost_usd,COALESCE(pc.name,'Otros') category FROM products p LEFT JOIN product_categories pc ON pc.id=p.category_id WHERE p.id=? AND p.active=1");$ovQ=$hasOverrides?$db->prepare('SELECT markup_percentage FROM product_price_overrides WHERE product_id=? AND price_list_id=?'):null;
  $items=[];$materials=0;$sort=0;foreach($_POST['items']??[] as $r){$productId=(int)($r['product_id']??0);$qty=(float)($r['quantity']??0);if(!$productId||$qty<=0)continue;$prodQ->execute([$productId]);$p=$prodQ->fetch();if(!$p)continue;$markup=$defaultMarkup;if($ovQ){$ovQ->execute([$productId,$listId]);$ov=$ovQ->fetchColumn();if($ov!==false)$markup=(float)$ov;}$defaultUnit=round((float)$p['cost_usd']*(1+$markup/100),2);$posted=$r['unit_price']??null;$unit=(is_numeric($posted)&&(float)$posted>=0)?round((float)$posted,2):$defaultUnit;$sub=round($qty*$unit,2);$materials+=$sub;$items[]=[$productId,$p['category'],$brand($p['category']),$p['sku'],$p['description'],$p['unit'],$qty,$unit,$listId,$sub,$sort++];}
  if(!$items)throw new Exception('Agregá al menos un producto.');$labor=max(0,(float)($_POST['labor_amount']??0));$laborDescription=trim((string)($_POST['labor_description']??''));$matMode=$_POST['materials_tax_mode']??'sin_iva';$matVat=(float)($_POST['materials_vat_rate']??21);$labMode=$_POST['labor_tax_mode']??'sin_iva';$labVat=(float)($_POST['labor_vat_rate']??21);$factor=static fn(string $m,float $v):float=>$m==='mas_iva'?1+$v/100:1;$matTotal=round($materials*$factor($matMode,$matVat),2);$labTotal=round($labor*$factor($labMode,$labVat),2);$total=$matTotal+$labTotal;$version=max(1,(int)($_POST['version_no']??1));$date=$_POST['quote_date']??date('Y-m-d');$status=$_POST['status']??'borrador';$category=$_POST['quote_category']??'general';$notes=trim((string)($_POST['notes']??''));$db->beginTransaction();
  if($a==='update_quote'){if(!$qid)throw new Exception('Presupuesto inválido.');$db->prepare('UPDATE quotes SET project_id=?,version_no=?,quote_category=?,currency="USD",quote_date=?,quote_families=?,quote_template_family=?,price_list_id=?,materials_amount=?,labor_amount=?,labor_description=?,subtotal=?,tax_mode="sin_iva",vat_rate=21,materials_tax_mode=?,materials_vat_rate=?,labor_tax_mode=?,labor_vat_rate=?,total=?,status=?,notes=? WHERE id=?')->execute([$pid,$version,$category,$date,implode(',',$families),$template,$listId,$materials,$labor,$laborDescription,$materials+$labor,$matMode,$matVat,$labMode,$labVat,$total,$status,$notes,$qid]);$db->prepare('DELETE FROM quote_items WHERE quote_id=?')->execute([$qid]);}else{$db->prepare('INSERT INTO quotes(project_id,version_no,quote_category,currency,quote_date,quote_families,quote_template_family,price_list_id,materials_amount,labor_amount,labor_description,subtotal,tax_mode,vat_rate,materials_tax_mode,materials_vat_rate,labor_tax_mode,labor_vat_rate,total,status,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$pid,$version,$category,'USD',$date,implode(',',$families),$template,$listId,$materials,$labor,$laborDescription,$materials+$labor,'sin_iva',21,$matMode,$matVat,$labMode,$labVat,$total,$status,$notes]);$qid=(int)$db->lastInsertId();}
  $ins=$db->prepare('INSERT INTO quote_items(quote_id,product_id,category,brand,sku,description,unit,quantity,unit_price,price_list_id,subtotal,sort_order) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)');foreach($items as $r)$ins->execute(array_merge([$qid],$r));
  if($status==='aprobado_inicial'){$pct=(float)$project['engineering_pct'];$amt=round($total*$pct/100,2);$db->prepare("INSERT INTO charges(project_id,quote_id,charge_date,type,currency,description,amount) VALUES(?,?,?,'ingenieria','USD',?,?)")->execute([$pid,$qid,$date,'Adelanto de ingeniería '.$pct.'% · v'.$version,$amt]);$eng=(int)$db->lastInsertId();$replaceCharge($db,$pid,$eng,['ingenieria']);$db->prepare("UPDATE projects SET status='aprobado' WHERE id=?")->execute([$pid]);}
  if($status==='final'){$db->prepare("INSERT INTO charges(project_id,quote_id,charge_date,type,currency,description,amount) VALUES(?,?,?,'materiales','USD',?,?)")->execute([$pid,$qid,$date,'Materiales · presupuesto final v'.$version,$matTotal]);$mat=(int)$db->lastInsertId();$replaceCharge($db,$pid,$mat,['materiales']);if($labTotal>0){$desc=$laborDescription!==''?$laborDescription:'Mano de obra';$db->prepare("INSERT INTO charges(project_id,quote_id,charge_date,type,currency,description,amount) VALUES(?,?,?,'mano_obra','USD',?,?)")->execute([$pid,$qid,$date,$desc.' · presupuesto final v'.$version,$labTotal]);$lab=(int)$db->lastInsertId();$replaceCharge($db,$pid,$lab,['ingenieria','mano_obra']);}$db->prepare("UPDATE projects SET status='en_obra' WHERE id=?")->execute([$pid]);}
  $db->commit();$_SESSION['msg']=$a==='update_quote'?'Presupuesto actualizado.':'Presupuesto creado.';$go('index.php?a=quote_view&id='.$qid);
 }catch(Throwable $ex){if($db->inTransaction())$db->rollBack();$_SESSION['msg']='No se pudo guardar: '.$ex->getMessage();$go('index.php?a='.($a==='update_quote'?'edit_quote&id='.$qid:'new_quote'));}
}
ob_start();require __DIR__.'/module_v5.php';$html=ob_get_clean();
$overrides=[];if(isset($db)&&$db instanceof PDO){try{foreach($db->query('SELECT product_id,price_list_id,markup_percentage FROM product_price_overrides') as $r)$overrides[(int)$r['product_id']][(int)$r['price_list_id']]=(float)$r['markup_percentage'];}catch(Throwable $e){}}
$json=json_encode($overrides,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);$inject=<<<HTML
<script>(function(){const productListOverrides=$json;window.productPrice=function(id){const p=products[id],l=lists[document.getElementById('priceList').value];if(!p||!l)return 0;const listId=Number(document.getElementById('priceList').value),ov=productListOverrides[id]&&productListOverrides[id][listId]!==undefined?Number(productListOverrides[id][listId]):null,markup=ov===null?Number(l.markup):ov;return Math.round(Number(p.cost)*(1+markup/100)*100)/100};if(typeof window.calc==='function')window.calc();})();</script>
HTML;
if(str_contains($html,'</body>'))$html=str_replace('</body>',$inject.'</body>',$html);else$html.=$inject;echo $html;