<?php
declare(strict_types=1);
session_start();
$root=dirname(__DIR__,3);
$cfg=require $root.'/config.php';
date_default_timezone_set($cfg['timezone']??'America/Argentina/Buenos_Aires');
$db=new PDO('mysql:host='.$cfg['db_host'].';dbname='.$cfg['db_name'].';charset=utf8mb4',$cfg['db_user'],$cfg['db_pass'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
if(empty($_SESSION['user'])){header('Location:index.php');exit;}
function e($v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function usd($n):string{return 'US$ '.number_format((float)$n,2,',','.');}
function imgData($data,$mime):string{return (!empty($data)&&!empty($mime))?'data:'.$mime.';base64,'.base64_encode($data):'';}
function taxTotal(float $base,string $mode,float $vat):float{return $mode==='mas_iva'?round($base*(1+$vat/100),2):$base;}
function taxLabel(string $baseLabel,string $mode):string{if($mode==='mas_iva')return $baseLabel.' + IVA';if($mode==='iva_incluido')return $baseLabel.' (IVA incluido)';return $baseLabel;}
$id=(int)($_GET['id']??0);
$s=$db->prepare("SELECT q.*,p.project_number,p.name project_name,p.engineering_pct,c.business_name,c.contact_name,c.cuit,c.email,c.whatsapp,c.address,c.city,c.province,pp.business_name partner_name,pl.name price_list_name FROM quotes q JOIN projects p ON p.id=q.project_id JOIN clients c ON c.id=p.client_id LEFT JOIN project_partners pp ON pp.id=p.partner_id LEFT JOIN price_lists pl ON pl.id=q.price_list_id WHERE q.id=?");
$s->execute([$id]);$q=$s->fetch();if(!$q)exit('Presupuesto inexistente.');
$s=$db->prepare("SELECT qi.*,p.image_data,p.image_mime FROM quote_items qi LEFT JOIN products p ON p.id=qi.product_id WHERE qi.quote_id=? ORDER BY qi.sort_order,qi.id");
$s->execute([$id]);$items=$s->fetchAll();
$logo='https://puntodomotica.com/assets/images/cropped-logo-blanco-63892739ae.png';
$print=($_GET['a']??'')==='quote_print';
$families=array_filter(array_map('trim',explode(',',(string)($q['quote_families']??''))));
$template=(string)($q['quote_template_family']??($families[0]??''));
$familyLabel=['lifesmart'=>'LifeSmart','control4'=>'Control4','shelly'=>'Shelly'][$template]??ucfirst($template);
$mat=(float)$q['materials_amount'];$lab=(float)$q['labor_amount'];
$matMode=(string)($q['materials_tax_mode']??'sin_iva');$matVat=(float)($q['materials_vat_rate']??21);
$labMode=(string)($q['labor_tax_mode']??'sin_iva');$labVat=(float)($q['labor_vat_rate']??21);
$matTotal=taxTotal($mat,$matMode,$matVat);$labTotal=taxTotal($lab,$labMode,$labVat);$total=(float)$q['total'];
?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Presupuesto <?=e($q['project_number'])?></title>
<style>
@page{size:A4;margin:0}*{box-sizing:border-box}body{margin:0;background:#e8e8e8;color:#202124;font-family:Aptos,"Segoe UI","Helvetica Neue",Arial,sans-serif;font-size:12px}.toolbar{width:210mm;margin:12px auto;display:flex;gap:8px;align-items:center}.toolbar a,.toolbar button{border:0;border-radius:7px;padding:10px 14px;background:#ff6702;color:#fff;text-decoration:none;font-weight:700;cursor:pointer}.toolbar .dark{background:#242122}.toolbar .light{background:#fff;color:#242122;border:1px solid #d4d4d4}.sheet{position:relative;width:210mm;min-height:297mm;margin:0 auto 20px;background:#fff;overflow:hidden;box-shadow:0 12px 34px rgba(0,0,0,.14)}
.top-orange{position:absolute;left:0;top:0;width:53mm;height:28mm;background:#ff6702;clip-path:polygon(0 0,100% 0,42% 100%,0 100%)}.top-black{position:absolute;left:0;top:0;width:143mm;height:43mm;background:#242122;clip-path:polygon(35% 0,100% 0,0 100%,0 64%)}.header{position:relative;z-index:3;height:45mm;padding:0 14mm}.logo{position:absolute;left:13mm;top:9mm;width:54mm;height:auto;display:block}.titlebox{position:absolute;right:14mm;top:12mm;text-align:right}.titlebox h1{margin:0;color:#ff6702;font-size:29px;line-height:1;font-weight:600}.titlebox .code{margin-top:3mm;font-size:10.5px;color:#45515d}
.meta-strip{position:relative;z-index:4;display:grid;grid-template-columns:1.2fr .56fr 1.25fr .72fr 1.15fr .7fr;gap:0;padding:0 14mm 6mm;margin-top:-3mm}.meta-item{padding:0 5mm;border-left:1.5px solid #ff6702;min-height:13mm}.meta-item:first-child{border-left:0;padding-left:0}.meta-item .k{display:block;font-weight:700;font-size:10.5px;margin-bottom:1mm}.meta-item .v{display:block;color:#33404b;font-size:10.7px;line-height:1.25}.meta-item .main{font-size:11.4px;font-weight:700;color:#202124}.meta-item .sub{margin-top:.8mm;color:#5b6570;font-size:10.2px}
.tablewrap{padding:0 14mm}.equipment{width:100%;border-collapse:collapse;table-layout:fixed}.equipment th{background:#ff6702;color:#fff;height:12mm;padding:0 4mm;text-align:left;font-size:10.8px;font-weight:700}.equipment td{height:18.5mm;border-bottom:1px solid #d7d7d7;padding:2.6mm 4mm;vertical-align:middle;font-size:11.8px;line-height:1.32}.equipment tbody tr:nth-child(even) td{background:#fbfbfb}.equipment .pic{width:15mm;text-align:center;padding:2mm}.equipment .pic img{max-width:12.5mm;max-height:13.5mm;object-fit:contain;display:block;margin:auto}.placeholder{width:11.5mm;height:11.5mm;border:1px solid #e4e4e4;border-radius:2px;background:#fff;margin:auto}.equipment .sku{width:27mm;font-weight:700;font-size:10.2px}.equipment .desc{width:auto;font-size:12px}.equipment .qty{width:16mm;text-align:center}.equipment .price{width:25mm;text-align:right;white-space:nowrap}.equipment .subtotal{width:27mm;text-align:right;font-weight:700;white-space:nowrap}
.section-subtotal{display:flex;justify-content:flex-end;gap:10mm;padding:3.5mm 18mm 0 0;font-size:11.5px}.section-subtotal span:first-child{color:#4f5963}.section-subtotal b{min-width:28mm;text-align:right}.labor{margin:7mm 14mm 0}.labor h3{margin:0 0 2.5mm;color:#ff6702;font-size:13.5px}.laborline{border-left:3px solid #ff6702;padding:2.5mm 4mm;min-height:9mm;font-size:11.7px;display:flex;align-items:center;justify-content:space-between;gap:10mm}.labor-description{flex:1}.labor-value{display:flex;align-items:center;gap:7mm;white-space:nowrap;color:#4f5963}.labor-value b{color:#202124;min-width:28mm;text-align:right}
.bottom{display:grid;grid-template-columns:1fr 70mm;gap:16mm;margin:8mm 14mm 27mm;align-items:start}.notes h3{margin:0 0 3mm;color:#ff6702;font-size:12.5px}.notes p{margin:0;white-space:pre-line;color:#4f565d;font-size:10.5px;line-height:1.5}.summary{font-size:11.5px}.summary .r{display:flex;justify-content:space-between;gap:8mm;padding:2.5mm 0}.summary .grand{border-top:1px solid #333;margin-top:3mm;padding-top:4mm;color:#ff6702;font-size:19px;font-weight:700}.footerbrand{position:absolute;left:14mm;bottom:10mm;color:#ff6702;font-weight:700;font-size:11.5px}.footnote{position:absolute;right:14mm;bottom:10mm;text-align:right;font-size:9.5px;color:#4d4d4d}.bottom-black{position:absolute;right:0;bottom:0;width:82mm;height:25mm;background:#242122;clip-path:polygon(42% 100%,100% 16%,100% 100%)}.bottom-orange{position:absolute;right:0;bottom:0;width:29mm;height:16mm;background:#ff6702;clip-path:polygon(35% 100%,100% 12%,100% 100%)}.screen-note{width:210mm;margin:0 auto 18px;background:#fff;border:1px solid #ddd;padding:10px 14px;font-size:12px}@media print{body{background:#fff}.toolbar,.screen-note{display:none!important}.sheet{margin:0;box-shadow:none}}
</style></head><body>
<?php if(!$print):?><div class="toolbar"><a class="light" href="?a=quotes">← Presupuestos</a><a class="dark" href="?a=edit_quote&id=<?=$id?>">Editar</a><button onclick="window.print()">Imprimir / Guardar PDF</button></div><?php endif;?>
<section class="sheet"><div class="top-orange"></div><div class="top-black"></div><header class="header"><img class="logo" src="<?=$logo?>" alt="Punto Domótica"><div class="titlebox"><h1>PRESUPUESTO</h1><div class="code"><?=e($q['project_number'])?> · v<?=e($q['version_no'])?></div></div></header>
<div class="meta-strip"><div class="meta-item"><span class="k">Cliente</span><span class="v main"><?=e($q['business_name'])?></span><?php if(!empty($q['city'])||!empty($q['province'])):?><span class="sub"><?=e(trim(($q['city']??'').(empty($q['city'])||empty($q['province'])?'':' · ').($q['province']??'')))?></span><?php endif;?></div><div class="meta-item"><span class="k">Proyecto</span><span class="v"><?=e($q['project_number'])?></span></div><div class="meta-item"><span class="k">Obra</span><span class="v"><?=e($q['project_name'])?></span></div><div class="meta-item"><span class="k">Fecha</span><span class="v"><?=e(date('d/m/Y',strtotime($q['quote_date'])))?></span></div><div class="meta-item"><span class="k">Arquitecto</span><span class="v"><?=e($q['partner_name']?:'—')?></span></div><div class="meta-item"><span class="k">Tecnología</span><span class="v"><?=e($familyLabel)?></span></div></div>
<div class="tablewrap"><table class="equipment"><thead><tr><th class="pic">Imagen</th><th class="sku">SKU</th><th class="desc">Descripción</th><th class="qty">Cant.</th><th class="price">Precio</th><th class="subtotal">Total</th></tr></thead><tbody><?php foreach($items as $it):$src=imgData($it['image_data']??null,$it['image_mime']??null);?><tr><td class="pic"><?php if($src):?><img src="<?=$src?>" alt=""><?php else:?><div class="placeholder"></div><?php endif;?></td><td class="sku"><?=e($it['sku']?:'—')?></td><td class="desc"><?=e($it['description'])?></td><td class="qty"><?=e(rtrim(rtrim(number_format((float)$it['quantity'],2,'.',''),'0'),'.'))?></td><td class="price"><?=usd($it['unit_price'])?></td><td class="subtotal"><?=usd($it['subtotal'])?></td></tr><?php endforeach;?></tbody></table></div><div class="section-subtotal"><span>Subtotal materiales</span><b><?=usd($mat)?></b></div>
<?php if($lab>0):?><div class="labor"><h3>Mano de obra</h3><div class="laborline"><span class="labor-description"><?=e($q['labor_description']?:'Configuración, montaje y diseño de escenas')?></span><span class="labor-value"><span>Subtotal mano de obra</span><b><?=usd($lab)?></b></span></div></div><?php endif;?>
<div class="bottom"><div class="notes"><?php if(trim((string)$q['notes'])!==''):?><h3>Observaciones</h3><p><?=e($q['notes'])?></p><?php endif;?></div><div class="summary"><div class="r"><span><?=e(taxLabel('Materiales',$matMode))?></span><b><?=usd($matTotal)?></b></div><?php if($lab>0):?><div class="r"><span><?=e(taxLabel('Mano de obra',$labMode))?></span><b><?=usd($labTotal)?></b></div><?php endif;?><div class="r grand"><span>TOTAL</span><span><?=usd($total)?></span></div></div></div><div class="footerbrand">Punto Domótica<div style="color:#444;font-weight:400;font-size:9.5px">Espacios inteligentes</div></div><div class="footnote">Valores expresados en dólares estadounidenses (USD)<br>Presupuesto <?=e($q['project_number'])?> · versión <?=e($q['version_no'])?></div><div class="bottom-black"></div><div class="bottom-orange"></div></section>
<?php if(!$print):?><div class="screen-note">Al generar el paquete final se usará el prólogo correspondiente a <b><?=e($familyLabel)?></b> antes de este presupuesto. La sección de forma de pago se anexará después del presupuesto.</div><?php endif;?><?php if($print):?><script>window.addEventListener('load',()=>setTimeout(()=>window.print(),350));</script><?php endif;?></body></html>