<?php
declare(strict_types=1);
session_start();
$root=dirname(__DIR__,3);
$cfg=require $root.'/config.php';
date_default_timezone_set($cfg['timezone']??'America/Argentina/Buenos_Aires');
if(empty($_SESSION['user'])){header('Location:index.php');exit;}
$permissions=$_SESSION['user']['permissions']??[];
$isAdmin=($_SESSION['user']['role']??'')==='admin';
$canView=$isAdmin||!empty($permissions['projects']['view'])||!empty($permissions['projects']['manage']);
if(!$canView){http_response_code(403);exit('Tu perfil no permite acceder a presupuestos.');}
$db=new PDO('mysql:host='.$cfg['db_host'].';dbname='.$cfg['db_name'].';charset=utf8mb4',$cfg['db_user'],$cfg['db_pass'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
function etq($v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function imgq($data,$mime):string{return(!empty($data)&&!empty($mime))?'data:'.$mime.';base64,'.base64_encode($data):'';}
$id=(int)($_GET['id']??0);
$s=$db->prepare("SELECT q.*,p.project_number,p.name project_name,c.business_name,pp.business_name partner_name FROM quotes q JOIN projects p ON p.id=q.project_id JOIN clients c ON c.id=p.client_id LEFT JOIN project_partners pp ON pp.id=p.partner_id WHERE q.id=?");
$s->execute([$id]);$q=$s->fetch();if(!$q){http_response_code(404);exit('Presupuesto inexistente.');}
$s=$db->prepare("SELECT qi.*,p.image_data,p.image_mime FROM quote_items qi LEFT JOIN products p ON p.id=qi.product_id WHERE qi.quote_id=? ORDER BY qi.block_order,qi.sort_order,qi.id");$s->execute([$id]);$items=$s->fetchAll();
$blocks=[];foreach($items as $it){$o=(int)($it['block_order']??0);if(!isset($blocks[$o]))$blocks[$o]=['type'=>'materials','title'=>$it['section_title']?:'Materiales','items'=>[]];$blocks[$o]['items'][]=$it;}ksort($blocks);
$family=trim((string)($q['quote_template_family']??''));if($family==='')$family=trim(explode(',',(string)($q['quote_families']??''))[0]??'');
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Detalle técnico <?=etq($q['project_number'])?></title><style>@page{size:A4;margin:0}*{box-sizing:border-box}body{margin:0;background:#eceff2;color:#202832;font-family:Aptos,"Segoe UI",Arial,sans-serif;font-size:12px}.toolbar{width:210mm;margin:12px auto;display:flex;gap:8px}.toolbar a,.toolbar button{border:0;border-radius:7px;padding:10px 14px;background:#ff6702;color:#fff;text-decoration:none;font-weight:700;cursor:pointer}.toolbar .light{background:#fff;color:#202832;border:1px solid #d8dde3}.sheet{width:210mm;min-height:297mm;margin:0 auto 20px;background:#fff;padding:18mm 15mm 16mm;box-shadow:0 12px 34px #0002}.head{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:3px solid #ff6702;padding-bottom:8mm;margin-bottom:7mm}.brand{width:58mm;line-height:0}.brand img{display:block;width:100%;height:auto;max-height:24mm;object-fit:contain;object-position:left center}.doc-title{text-align:right}.doc-title h1{margin:0;color:#ff6702;font-size:25px}.doc-title div{margin-top:2mm;color:#66717d}.meta{display:grid;grid-template-columns:1fr 1fr 1fr;gap:6mm;margin-bottom:8mm}.meta-box{padding:4mm;border:1px solid #e0e4e8;border-radius:8px}.meta-box small{display:block;color:#6f7882;text-transform:uppercase;font-size:9px;font-weight:700}.meta-box b{display:block;margin-top:1mm;font-size:11px}.section{margin:0 0 7mm}.section h2{font-size:13px;margin:0;background:#f1f3f5;border-left:4px solid #ff6702;padding:3mm 4mm}.equipment{width:100%;border-collapse:collapse;table-layout:fixed}.equipment th{background:#252b31;color:#fff;text-align:left;padding:2.6mm;font-size:9.5px}.equipment td{border-bottom:1px solid #e0e4e8;padding:2.8mm;vertical-align:middle}.equipment .pic{width:16mm;text-align:center}.equipment .pic img{max-width:12mm;max-height:12mm;object-fit:contain}.equipment .sku{width:28mm;font-weight:700}.equipment .qty{width:18mm;text-align:center;font-weight:700}.foot{margin-top:12mm;padding-top:5mm;border-top:1px solid #d9dde1;color:#6f7882;font-size:9.5px}.note{width:210mm;margin:0 auto 20px;background:#fff;padding:10px 14px;border:1px solid #d8dde3}.no-finance{font-weight:700;color:#5f6872}@media(max-width:900px){.toolbar,.sheet,.note{width:100%;margin-left:0;margin-right:0}.sheet{min-height:0;padding:22px}.meta{grid-template-columns:1fr}}
@media print{
 body{background:#fff;-webkit-print-color-adjust:exact;print-color-adjust:exact}
 .toolbar,.note{display:none!important}
 .sheet{width:210mm;min-height:297mm;margin:0;background:#fff;padding:18mm 15mm 16mm;box-shadow:none}
 .meta{grid-template-columns:1fr 1fr 1fr}
 .head,.meta-box,.section,.equipment thead,.equipment tr,.foot{break-inside:avoid;page-break-inside:avoid}
 .equipment thead{display:table-header-group}
 .equipment tr{break-inside:avoid;page-break-inside:avoid}
 .section h2{break-after:avoid;page-break-after:avoid}
}</style></head><body><div class="toolbar"><a class="light" href="?a=project&id=<?=$q['project_id']?>">← Volver al proyecto</a><button type="button" onclick="window.print()">Descargar / imprimir PDF técnico</button></div><section class="sheet" id="technicalSheet"><div class="head"><div class="brand"><img src="assets/punto-domotica-logo.svg" alt="Punto Domótica"></div><div class="doc-title"><h1>DETALLE TÉCNICO</h1><div><?=etq($q['project_number'])?> · v<?=etq($q['version_no'])?></div></div></div><div class="meta"><div class="meta-box"><small>Cliente</small><b><?=etq($q['business_name'])?></b></div><div class="meta-box"><small>Proyecto</small><b><?=etq($q['project_name'])?></b></div><div class="meta-box"><small>Fecha</small><b><?=etq(date('d/m/Y',strtotime($q['quote_date'])))?></b></div><div class="meta-box"><small>Arquitecto / constructora</small><b><?=etq($q['partner_name']?:'Sin asignar')?></b></div><div class="meta-box"><small>Tecnología</small><b><?=etq($family?:'—')?></b></div><div class="meta-box"><small>Estado</small><b><?=etq($q['status'])?></b></div></div><?php foreach($blocks as $b):?><div class="section"><h2><?=etq($b['title'])?></h2><table class="equipment"><thead><tr><th class="pic">Imagen</th><th class="sku">SKU</th><th>Descripción</th><th class="qty">Cant.</th></tr></thead><tbody><?php foreach($b['items'] as $it):$im=imgq($it['image_data']??null,$it['image_mime']??null);?><tr><td class="pic"><?php if($im):?><img src="<?=$im?>" alt=""><?php endif;?></td><td class="sku"><?=etq($it['sku']?:'—')?></td><td><?=etq($it['description'])?></td><td class="qty"><?=etq(rtrim(rtrim(number_format((float)$it['quantity'],2,'.',''),'0'),'.'))?></td></tr><?php endforeach;?></tbody></table></div><?php endforeach;?><div class="foot"><span class="no-finance">Documento técnico sin información comercial ni financiera.</span><br>Incluye únicamente equipos y cantidades contemplados en el presupuesto.</div></section><div class="note">Esta vista está pensada para perfiles técnicos y Project Managers. No muestra precios de productos, subtotales, IVA, totales ni condiciones comerciales.</div></body></html>