<?php
declare(strict_types=1);
session_start();
$root=dirname(__DIR__,3);$cfg=require $root.'/config.php';date_default_timezone_set($cfg['timezone']??'America/Argentina/Buenos_Aires');
if(empty($_SESSION['user'])){header('Location:index.php');exit;}
$permissions=$_SESSION['user']['permissions']??[];$allowed=($_SESSION['user']['role']??'')==='admin'||!empty($permissions['projects']['view'])||!empty($permissions['projects']['manage']);
if(!$allowed){http_response_code(403);exit('Tu perfil no permite acceder a proyectos.');}
$db=new PDO('mysql:host='.$cfg['db_host'].';dbname='.$cfg['db_name'].';charset=utf8mb4',$cfg['db_user'],$cfg['db_pass'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
$id=(int)($_GET['id']??0);$s=$db->prepare('SELECT p.*,c.business_name,c.contact_name,c.cuit,c.email,c.whatsapp FROM projects p JOIN clients c ON c.id=p.client_id WHERE p.id=?');$s->execute([$id]);$project=$s->fetch();if(!$project){http_response_code(404);exit('Proyecto inexistente.');}
$s=$db->prepare("SELECT * FROM quotes WHERE project_id=? AND status IN ('aprobado_inicial','aprobado_definitivo','final') ORDER BY quote_date,id");$s->execute([$id]);$quotes=$s->fetchAll();
$s=$db->prepare('SELECT * FROM payments WHERE project_id=? ORDER BY payment_date,id');$s->execute([$id]);$payments=$s->fetchAll();
$s=$db->prepare('SELECT c.*,COALESCE((SELECT SUM(a.amount) FROM allocations a WHERE a.charge_id=c.id),0) paid FROM charges c WHERE c.project_id=? AND c.active=1');$s->execute([$id]);$charges=$s->fetchAll();
$totals=[];foreach(['USD','ARS'] as $cur)$totals[$cur]=['approved'=>0.0,'materials'=>0.0,'materials_vat'=>0.0,'labor'=>0.0,'labor_vat'=>0.0,'paid'=>0.0,'materials_paid'=>0.0,'labor_paid'=>0.0,'due_now'=>0.0];
$approvedIds=[];foreach($quotes as $q){$cur=$q['currency']??'USD';if(!isset($totals[$cur]))continue;$mi=(float)$q['materials_amount'];$li=(float)$q['labor_amount'];$mv=($q['materials_tax_mode']??'')==='mas_iva'?round($mi*(float)($q['materials_vat_rate']??21)/100,2):0.0;$lv=($q['labor_tax_mode']??'')==='mas_iva'?round($li*(float)($q['labor_vat_rate']??21)/100,2):0.0;$totals[$cur]['materials']+=$mi;$totals[$cur]['materials_vat']+=$mv;$totals[$cur]['labor']+=$li;$totals[$cur]['labor_vat']+=$lv;$totals[$cur]['approved']+=$mi+$mv+$li+$lv;$approvedIds[(int)$q['id']]=true;}
foreach($payments as $p){$cur=$p['currency'];if(isset($totals[$cur]))$totals[$cur]['paid']+=(float)$p['amount'];}
foreach($charges as $c){$cur=$c['currency'];if(!isset($totals[$cur]))continue;$qid=(int)($c['quote_id']??0);if($qid>0&&!isset($approvedIds[$qid]))continue;$paid=(float)$c['paid'];$totals[$cur]['due_now']+=max(0,(float)$c['amount']-$paid);if($c['type']==='materiales')$totals[$cur]['materials_paid']+=$paid;elseif(in_array($c['type'],['ingenieria','mano_obra'],true))$totals[$cur]['labor_paid']+=$paid;}
function es($v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function amount($n,string $cur):string{return ($cur==='USD'?'US$ ':'$ ').number_format((float)$n,2,',','.');}
$statusLabels=['aprobado_inicial'=>'Aceptado inicial','aprobado_definitivo'=>'Aceptado definitivo','final'=>'Aceptado definitivo'];
$conceptLabels=['general'=>'Pago general','anticipo'=>'Anticipo','parcial'=>'Pago parcial','saldo'=>'Pago de saldo','ingenieria'=>'Pago de ingeniería','otro'=>'Otro pago'];
$contact=trim((string)($project['contact_name']??''))?:trim((string)$project['business_name']);
$email=trim((string)($project['email']??''));
$whatsapp=preg_replace('/\D+/','',(string)($project['whatsapp']??''))??'';
$shareSubject='Estado de cuenta · '.$project['project_number'].' · Punto Domótica';
$shareText='Hola '.$contact.', te enviamos el estado de cuenta actualizado del proyecto '.$project['project_number'].' · '.$project['name'].'.';
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Estado de cuenta · <?=es($project['project_number'])?></title><style>
@page{size:A4;margin:13mm}*{box-sizing:border-box}body{margin:0;background:#edf0f3;color:#202832;font:13px/1.45 Arial,sans-serif}.toolbar{max-width:900px;margin:18px auto;display:flex;justify-content:space-between;align-items:center;gap:10px}.toolbar-actions{display:flex;flex-wrap:wrap;justify-content:flex-end;gap:9px}.btn{border:0;border-radius:8px;padding:11px 16px;background:#ff6702;color:#fff;text-decoration:none;font-weight:700;cursor:pointer}.btn.light{background:#fff;color:#27303b}.btn.green{background:#15815c}.sheet{width:210mm;max-width:calc(100% - 24px);min-height:297mm;margin:0 auto 28px;background:#fff;padding:15mm;box-shadow:0 5px 24px #0002}.head{display:flex;justify-content:space-between;gap:25px;align-items:flex-start;border-bottom:4px solid #ff6702;padding-bottom:18px}.logo{width:215px;max-width:46%;height:auto}.doc{text-align:right}.doc h1{font-size:25px;margin:0 0 5px}.muted{color:#707984}.meta{display:grid;grid-template-columns:1fr 1fr;gap:12px 30px;padding:20px 0}.meta small{display:block;text-transform:uppercase;color:#78818b;font-size:10px;font-weight:bold}.meta b{font-size:14px}.currency{margin-top:16px;page-break-inside:avoid}.currency h2{font-size:18px;margin:0 0 10px}.summary{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.box{border:1px solid #dfe3e7;border-radius:10px;padding:13px}.box span{display:block;color:#727c86;font-size:11px}.box strong{display:block;font-size:20px;margin-top:5px}.green{color:#15815c}.red{color:#b43a3a}.detail{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:10px}.detail .box strong{font-size:13px}.detail p{margin:6px 0 0}.section{margin-top:24px}.section h2{font-size:17px;border-bottom:2px solid #252b32;padding-bottom:7px;margin-bottom:5px}table{width:100%;border-collapse:collapse}th,td{padding:8px 6px;border-bottom:1px solid #e4e7ea;text-align:left;vertical-align:top}th{font-size:10px;text-transform:uppercase;color:#747d87}.right{text-align:right}.foot{margin-top:30px;padding-top:13px;border-top:1px solid #ddd;color:#747d87;font-size:10px}.empty{color:#747d87;padding:14px 0}@media(max-width:700px){.toolbar{align-items:stretch;flex-direction:column}.toolbar-actions{justify-content:stretch}.toolbar-actions .btn{flex:1;text-align:center}.summary,.detail,.meta{grid-template-columns:1fr}.sheet{padding:22px}.doc h1{font-size:19px}}@media print{body{background:#fff}.toolbar{display:none}.sheet{width:auto;max-width:none;min-height:0;margin:0;padding:0;box-shadow:none}.currency,.box,tr{break-inside:avoid}}
</style></head><body><div class="toolbar"><a class="btn light" href="?a=project&id=<?=$id?>">← Volver al proyecto</a><div class="toolbar-actions"><button class="btn" type="button" onclick="window.print()">Descargar / imprimir PDF</button><button class="btn light" type="button" onclick="shareStatement('email')">Enviar por email</button><button class="btn green" type="button" onclick="shareStatement('whatsapp')">Enviar por WhatsApp</button></div></div><main class="sheet"><header class="head"><img class="logo" src="assets/punto-domotica-logo.svg" alt="Punto Domótica"><div class="doc"><h1>ESTADO DE CUENTA</h1><div><?=es(date('d/m/Y'))?></div><div><?=es($project['project_number'])?></div></div></header><section class="meta"><div><small>Cliente</small><b><?=es($project['business_name'])?></b><?=!empty($project['contact_name'])?'<br>'.es($project['contact_name']):''?></div><div><small>Proyecto</small><b><?=es($project['project_number'].' · '.$project['name'])?></b></div><?php if($project['cuit']):?><div><small>CUIT / Documento</small><b><?=es($project['cuit'])?></b></div><?php endif;?><div><small>Estado del proyecto</small><b><?=es(str_replace('_',' ',$project['status']))?></b></div></section>
<?php foreach(['USD','ARS'] as $cur):$t=$totals[$cur];if($t['approved']<.009&&$t['paid']<.009)continue;$balance=$t['approved']-$t['paid'];$materialsTotal=$t['materials']+$t['materials_vat'];$laborTotal=$t['labor']+$t['labor_vat'];?><section class="currency"><h2>Resumen en <?=$cur?></h2><div class="summary"><div class="box"><span>Valor aprobado</span><strong><?=amount($t['approved'],$cur)?></strong></div><div class="box"><span>Total pagado</span><strong class="green"><?=amount($t['paid'],$cur)?></strong></div><div class="box"><span><?=$balance>=0?'Saldo pendiente':'Saldo a favor'?></span><strong class="<?=$balance>=0?'red':'green'?>"><?=amount(abs($balance),$cur)?></strong></div></div><div class="detail"><div class="box"><span>Materiales</span><p>Importe: <b><?=amount($t['materials'],$cur)?></b><br>IVA: <b><?=amount($t['materials_vat'],$cur)?></b><br>Total: <b><?=amount($materialsTotal,$cur)?></b><br>Pagado aplicado: <b class="green"><?=amount($t['materials_paid'],$cur)?></b></p></div><div class="box"><span>Mano de obra e ingeniería</span><p>Importe: <b><?=amount($t['labor'],$cur)?></b><br>IVA: <b><?=amount($t['labor_vat'],$cur)?></b><br>Total: <b><?=amount($laborTotal,$cur)?></b><br>Pagado aplicado: <b class="green"><?=amount($t['labor_paid'],$cur)?></b></p></div></div></section><?php endforeach;?>
<section class="section"><h2>Presupuestos aceptados</h2><?php if($quotes):?><table><thead><tr><th>Fecha</th><th>Presupuesto</th><th>Rubro</th><th>Estado</th><th class="right">Total</th></tr></thead><tbody><?php foreach($quotes as $q):?><tr><td><?=es(date('d/m/Y',strtotime($q['quote_date'])))?></td><td><b><?=es($q['proposal_name']?:'Presupuesto')?></b><br><span class="muted">Versión <?=es($q['version_no'])?></span></td><td><?=es($q['quote_category']?:'General')?></td><td><?=es($statusLabels[$q['status']]??$q['status'])?></td><td class="right"><b><?=amount($q['total'],$q['currency'])?></b></td></tr><?php endforeach;?></tbody></table><?php else:?><div class="empty">No hay presupuestos aceptados.</div><?php endif;?></section>
<section class="section"><h2>Pagos y recibos</h2><?php if($payments):?><table><thead><tr><th>Fecha</th><th>Recibo</th><th>Concepto / medio</th><th>Referencia</th><th class="right">Importe</th></tr></thead><tbody><?php foreach($payments as $p):?><tr><td><?=es(date('d/m/Y',strtotime($p['payment_date'])))?></td><td><b><?=es($p['receipt_number'])?></b></td><td><?=es($conceptLabels[$p['payment_concept']??'general']??'Pago')?> · <?=es(ucfirst($p['method']))?></td><td><?=es($p['reference']?:'—')?></td><td class="right"><b><?=amount($p['amount'],$p['currency'])?></b></td></tr><?php endforeach;?></tbody></table><?php else:?><div class="empty">No hay pagos registrados.</div><?php endif;?></section><footer class="foot">Documento informativo emitido por Punto Domótica. Los importes reflejan los presupuestos aceptados y pagos registrados en el sistema a la fecha de emisión.</footer></main><script>
const statementShare=<?=json_encode(['email'=>$email,'whatsapp'=>$whatsapp,'subject'=>$shareSubject,'text'=>$shareText],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>;
function shareStatement(channel){
 if(channel==='email'&&!statementShare.email){alert('El cliente no tiene un email cargado.');return;}
 if(channel==='whatsapp'&&!statementShare.whatsapp){alert('El cliente no tiene un WhatsApp cargado.');return;}
 window.print();
 const attachment='\n\nAdjuntá el estado de cuenta en PDF que acabás de guardar.';
 setTimeout(()=>{
  if(channel==='email')location.href='mailto:'+encodeURIComponent(statementShare.email)+'?subject='+encodeURIComponent(statementShare.subject)+'&body='+encodeURIComponent(statementShare.text+attachment);
  else window.open('https://wa.me/'+statementShare.whatsapp+'?text='+encodeURIComponent(statementShare.text+attachment),'_blank','noopener');
 },250);
}
</script></body></html>
