<?php
declare(strict_types=1);
$root=dirname(__DIR__,3);$cfg=require $root.'/config.php';$projectId=(int)($_GET['id']??0);$followups=[];
try{
 $dbFollowup=new PDO('mysql:host='.$cfg['db_host'].';dbname='.$cfg['db_name'].';charset=utf8mb4',$cfg['db_user'],$cfg['db_pass'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
 $pending=$dbFollowup->prepare("SELECT id,sent_at FROM quotes WHERE project_id=? AND status='enviado' AND sent_at IS NOT NULL AND next_followup_date IS NULL AND followup_closed_at IS NULL");$pending->execute([$projectId]);$schedule=$dbFollowup->prepare('UPDATE quotes SET next_followup_date=? WHERE id=? AND next_followup_date IS NULL');
 foreach($pending as $row){$date=new DateTimeImmutable((string)$row['sent_at']);$days=0;while($days<10){$date=$date->modify('+1 day');if((int)$date->format('N')<=5)$days++;}$schedule->execute([$date->format('Y-m-d'),(int)$row['id']]);}
 $stmt=$dbFollowup->prepare("SELECT q.id,q.proposal_name,q.version_no,q.status,q.sent_at,q.next_followup_date,q.followup_closed_at,u.name responsible_name,(SELECT h.notes FROM quote_followup_history h WHERE h.quote_id=q.id AND h.notes IS NOT NULL AND TRIM(h.notes)<>'' ORDER BY h.event_date DESC,h.id DESC LIMIT 1) last_note FROM quotes q LEFT JOIN users u ON u.id=q.responsible_user_id WHERE q.project_id=? ORDER BY CASE WHEN q.followup_closed_at IS NULL AND q.next_followup_date IS NOT NULL THEN 0 ELSE 1 END,q.next_followup_date IS NULL,q.next_followup_date,q.id DESC");$stmt->execute([$projectId]);$followups=$stmt->fetchAll();
}catch(Throwable $ignored){}
ob_start();require __DIR__.'/detail_v5.php';$html=ob_get_clean();
$e=static fn($value):string=>htmlspecialchars((string)$value,ENT_QUOTES,'UTF-8');$statusLabels=['borrador'=>'Borrador','enviado'=>'Enviado','aprobado_inicial'=>'Aceptado inicial','aprobado_definitivo'=>'Aceptado definitivo','final'=>'Aceptado definitivo','rechazado'=>'Rechazado'];$today=date('Y-m-d');$rows='';$dueCount=0;
foreach($followups as $item){$isOpen=empty($item['followup_closed_at'])&&!empty($item['next_followup_date']);$isDue=$isOpen&&$item['next_followup_date']<=$today;if($isDue)$dueCount++;$name=trim((string)($item['proposal_name']??''))?:('Presupuesto v'.(int)$item['version_no']);if(!empty($item['followup_closed_at']))$next='<span class="pill">Cerrado</span>';elseif(!empty($item['next_followup_date']))$next='<span class="pill" style="'.($isDue?'background:#ffe5e5;color:#a92727':'').'">'.($isDue?'Contactar · ':'').$e(date('d/m/Y',strtotime($item['next_followup_date']))).'</span>';elseif($item['status']==='borrador')$next='<span class="muted">Se programa al enviarlo</span>';else $next='<span class="muted">Sin programar</span>';$sent=$item['sent_at']?date('d/m/Y',strtotime($item['sent_at'])):'—';$note=trim((string)($item['last_note']??''));$rows.='<tr'.($isDue?' style="background:#fff7f2"':'').'><td><b>'.$e($name).'</b><br><small class="muted">v'.(int)$item['version_no'].' · '.$e($statusLabels[$item['status']]??$item['status']).'</small></td><td>'.$e($sent).'</td><td>'.$next.'</td><td>'.$e($item['responsible_name']?:'Sin asignar').'</td><td>'.($note!==''?$e($note):'<span class="muted">—</span>').'</td><td><a class="btn light" href="?a=quote_followup&id='.(int)$item['id'].'">Gestionar</a></td></tr>';}
if($rows==='')$rows='<tr><td colspan="6" class="muted">Este proyecto todavía no tiene presupuestos para seguir.</td></tr>';$summary=$dueCount>0?'<b style="color:#a92727">'.$dueCount.' contacto'.($dueCount===1?'':'s').' pendiente'.($dueCount===1?'':'s').'</b>':'<span class="muted">Sin contactos vencidos</span>';
$card='<section class="card" id="seguimiento-comercial"><div class="actions"><div style="flex:1"><h2 style="margin-bottom:4px">Seguimiento del cliente</h2><p class="muted" style="margin-top:0">Al enviar un presupuesto se agenda automáticamente el próximo contacto a 10 días hábiles. '.$summary.'</p></div><a class="btn light" href="?a=followup_agenda&project_id='.$projectId.'">Ver agenda</a></div><div class="scroll"><table><tr><th>Presupuesto</th><th>Enviado</th><th>Próximo contacto</th><th>Responsable</th><th>Última nota</th><th>Acción</th></tr>'.$rows.'</table></div></section>';
$marker='<div class="card"><div class="actions"><h2 style="flex:1">Presupuestos';$position=strpos($html,$marker);if($position!==false)$html=substr($html,0,$position).$card.substr($html,$position);elseif(str_contains($html,'</main>'))$html=str_replace('</main>',$card.'</main>',$html);else$html.=$card;echo $html;
