<?php
declare(strict_types=1);
session_start();
$root=dirname(__DIR__,3);$cfg=require $root.'/config.php';date_default_timezone_set($cfg['timezone']??'America/Argentina/Buenos_Aires');
$db=new PDO('mysql:host='.$cfg['db_host'].';dbname='.$cfg['db_name'].';charset=utf8mb4',$cfg['db_user'],$cfg['db_pass'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
if(empty($_SESSION['user'])){header('Location:index.php');exit;}
require_once $root.'/app/Core/UnifiedSidebar.php';
function e($v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function money($n,string $cur='USD'):string{return ($cur==='USD'?'US$ ':'$ ').number_format((float)$n,2,',','.');}
function canManageProjectV2():bool{if(($_SESSION['user']['role']??'')==='admin')return true;$p=$_SESSION['user']['permissions']??[];return !empty($p['projects']['manage']);}
function canManagePaymentsV2():bool{if(($_SESSION['user']['role']??'')==='admin')return true;$p=$_SESSION['user']['permissions']??[];return !empty($p['payments']['manage'])||!empty($p['receipts']['manage']);}
function calcProjectTotalsV2(array $quotes,array $charges,array $payments):array{
 $out=[];foreach(['ARS','USD'] as $cur)$out[$cur]=['project_total'=>0.0,'paid'=>0.0,'due_now'=>0.0,'materials'=>0.0,'materials_input'=>0.0,'materials_vat'=>0.0,'materials_paid'=>0.0,'materials_tax'=>[],'labor'=>0.0,'labor_input'=>0.0,'labor_vat'=>0.0,'labor_paid'=>0.0,'labor_tax'=>[],'other'=>0.0,'inferred'=>false];
 $hasPayments=[];foreach($payments as $p)$hasPayments[$p['currency']]=($hasPayments[$p['currency']]??0)+(float)$p['amount'];
 $approved=[];$fallback=[];
 foreach($quotes as $q){$cur=$q['currency']??'USD';$key=($q['quote_category']??'general').'|'.$cur;$status=(string)($q['status']??'');if(in_array($status,['aprobado_inicial','final'],true)){if(!isset($approved[$key]))$approved[$key]=$q;}elseif(!in_array($status,['rechazado','cancelado'],true)){if(!isset($fallback[$key]))$fallback[$key]=$q;}}
 $current=$approved;
 foreach($fallback as $key=>$q){if(isset($current[$key]))continue;$cur=$q['currency']??'USD';if(($hasPayments[$cur]??0)>0){$current[$key]=$q;$out[$cur]['inferred']=true;}}
 $taxNames=['sin_iva'=>'Sin IVA','iva_incluido'=>'IVA incluido','mas_iva'=>'Más IVA'];
 foreach($current as $q){$cur=$q['currency']??'USD';if(!isset($out[$cur]))continue;$mm=$q['materials_tax_mode']??$q['tax_mode']??'sin_iva';$lm=$q['labor_tax_mode']??$q['tax_mode']??'sin_iva';$mr=(float)($q['materials_vat_rate']??$q['vat_rate']??21);$lr=(float)($q['labor_vat_rate']??$q['vat_rate']??21);$mi=(float)$q['materials_amount'];$li=(float)$q['labor_amount'];$mv=$mm==='mas_iva'?round($mi*$mr/100,2):0.0;$lv=$lm==='mas_iva'?round($li*$lr/100,2):0.0;$mt=$mi+$mv;$lt=$li+$lv;$out[$cur]['materials_input']+=$mi;$out[$cur]['materials_vat']+=$mv;$out[$cur]['materials']+=$mt;$out[$cur]['labor_input']+=$li;$out[$cur]['labor_vat']+=$lv;$out[$cur]['labor']+=$lt;$out[$cur]['project_total']+=$mt+$lt;$ml=($taxNames[$mm]??$mm).($mm==='mas_iva'?' '.number_format($mr,2,',','.').'%':'');$ll=($taxNames[$lm]??$lm).($lm==='mas_iva'?' '.number_format($lr,2,',','.').'%':'');$out[$cur]['materials_tax'][$ml]=true;$out[$cur]['labor_tax'][$ll]=true;}
 foreach($charges as $c){if(empty($c['active']))continue;$cur=$c['currency'];if(!isset($out[$cur]))continue;$paid=(float)($c['paid']??0);$out[$cur]['due_now']+=max(0,(float)$c['amount']-$paid);if($c['type']==='materiales')$out[$cur]['materials_paid']+=$paid;elseif(in_array($c['type'],['ingenieria','mano_obra','obra'],true))$out[$cur]['labor_paid']+=$paid;if(empty($c['quote_id'])){$amount=(float)$c['amount'];$out[$cur]['project_total']+=$amount;if($c['type']==='materiales'){$out[$cur]['materials']+=$amount;$out[$cur]['materials_input']+=$amount;$out[$cur]['materials_tax']['Cargo manual']=true;}elseif(in_array($c['type'],['ingenieria','mano_obra','obra'],true)){$out[$cur]['labor']+=$amount;$out[$cur]['labor_input']+=$amount;$out[$cur]['labor_tax']['Cargo manual']=true;}else $out[$cur]['other']+=$amount;}}
 foreach($payments as $p){$cur=$p['currency'];if(!isset($out[$cur]))continue;$amount=(float)$p['amount'];$allocated=(float)($p['allocated']??0);$out[$cur]['paid']+=$amount;$unallocated=max(0,$amount-$allocated);if($unallocated>.009){$laborRoom=max(0,$out[$cur]['labor']-$out[$cur]['labor_paid']);$toLabor=min($laborRoom,$unallocated);$out[$cur]['labor_paid']+=$toLabor;$unallocated-=$toLabor;if($unallocated>.009){$matRoom=max(0,$out[$cur]['materials']-$out[$cur]['materials_paid']);$toMat=min($matRoom,$unallocated);$out[$cur]['materials_paid']+=$toMat;}}}
 return $out;
}
$id=(int)($_GET['id']??0);
$s=$db->prepare('SELECT p.*,c.business_name,pp.business_name partner_name FROM projects p JOIN clients c ON c.id=p.client_id LEFT JOIN project_partners pp ON pp.id=p.partner_id WHERE p.id=?');$s->execute([$id]);$project=$s->fetch();if(!$project){http_response_code(404);exit('Proyecto inexistente.');}
$s=$db->prepare('SELECT * FROM quotes WHERE project_id=? ORDER BY version_no DESC,id DESC');$s->execute([$id]);$quotes=$s->fetchAll();
$s=$db->prepare('SELECT c.*,COALESCE(SUM(a.amount),0) paid FROM charges c LEFT JOIN allocations a ON a.charge_id=c.id WHERE c.project_id=? GROUP BY c.id ORDER BY c.currency,c.charge_date,c.id');$s->execute([$id]);$charges=$s->fetchAll();
$s=$db->prepare('SELECT p.*,cl.email,cl.whatsapp,COALESCE((SELECT SUM(a.amount) FROM allocations a WHERE a.payment_id=p.id),0) allocated FROM payments p JOIN projects pr ON pr.id=p.project_id JOIN clients cl ON cl.id=pr.client_id WHERE p.project_id=? ORDER BY p.payment_date DESC,p.id DESC');$s->execute([$id]);$payments=$s->fetchAll();
$totals=calcProjectTotalsV2($quotes,$charges,$payments);$msg=$_SESSION['msg']??null;unset($_SESSION['msg']);
$taxLabels=['sin_iva'=>'Sin IVA','iva_incluido'=>'IVA incluido','mas_iva'=>'Más IVA'];$categoryLabels=['general'=>'General','domotica'=>'Domótica','redes'=>'Redes','camaras'=>'Cámaras','alarma'=>'Alarma','audio'=>'Audio'];
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($project['project_number'])?> · Punto ERP</title><style><?=erpSidebarCss()?>body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.45 system-ui,-apple-system,Segoe UI,sans-serif}.main{margin-left:var(--sidebar);padding:32px 4%}.card{background:#fff;border:1px solid var(--line);border-radius:14px;padding:22px;margin-bottom:18px;box-shadow:0 4px 16px #00000008}.grid{display:grid;grid-template-columns:repeat(12,1fr);gap:16px}.c4{grid-column:span 4}.c6{grid-column:span 6}.actions{display:flex;gap:9px;align-items:center;flex-wrap:wrap}.btn{display:inline-block;border:0;border-radius:8px;padding:10px 15px;background:var(--o);color:#fff;text-decoration:none;font-weight:700}.btn.light{background:#edf0f3;color:var(--ink)}.muted{color:var(--muted)}.kpi{font-size:26px;font-weight:760;margin-top:6px}.ok{color:#15815c}.bad{color:#bf3c3c}.pill{display:inline-block;padding:4px 9px;border-radius:20px;background:#edf0f3;font-size:12px}.notice{padding:11px 14px;border-radius:9px;background:#fff7ef;border:1px solid #ffd2b1;margin:0 0 18px}.flash{padding:12px 15px;background:#fff0e5;border:1px solid #ffd2b1;border-radius:9px;margin-bottom:18px}.scroll{overflow:auto}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:11px 9px;border-bottom:1px solid var(--line);vertical-align:top}th{font-size:12px;text-transform:uppercase;color:var(--muted)}.right{text-align:right}@media(max-width:900px){.main{margin-left:0;padding:22px 18px}.c4,.c6{grid-column:span 12}}</style></head><body><?php erpSidebar('project');?><main class="main"><?php if($msg):?><div class="flash"><?=e($msg)?></div><?php endif;?><div class="actions"><div style="flex:1"><span class="muted"><?=e($project['business_name'])?><?=!empty($project['partner_name'])?' · '.e($project['partner_name']):''?></span><h1><?=e($project['project_number'])?> · <?=e($project['name'])?></h1></div><?php if(canManageProjectV2()):?><a class="btn light" href="?a=edit_project&id=<?=$id?>">Editar proyecto</a><?php endif;?><span class="pill"><?=e($project['status'])?></span></div>
<?php foreach(['USD','ARS'] as $cur):$t=$totals[$cur];if($t['project_total']<.009&&$t['paid']<.009&&$t['due_now']<.009)continue;$balance=$t['project_total']-$t['paid'];?><h2><?=e($cur)?></h2><?php if($t['inferred']):?><div class="notice"><b>Presupuesto vigente tomado para el saldo.</b> Como este proyecto ya tiene pagos registrados, el sistema está tomando el último presupuesto activo aunque todavía figure como borrador.</div><?php endif;?><div class="grid"><div class="card c4"><span class="muted">Valor vigente del proyecto</span><div class="kpi"><?=money($t['project_total'],$cur)?></div></div><div class="card c4"><span class="muted">Pagado por el cliente</span><div class="kpi ok"><?=money($t['paid'],$cur)?></div></div><div class="card c4"><span class="muted"><?=$balance>=0?'Saldo total pendiente':'Saldo a favor del cliente'?></span><div class="kpi <?=$balance>=0?'bad':'ok'?>"><?=money(abs($balance),$cur)?></div></div></div><div class="card"><div class="actions"><div style="flex:1"><h3 style="margin:0">Detalle del saldo</h3><p class="muted" style="margin:5px 0 0">El adelanto de ingeniería se aplica a Mano de obra e ingeniería.</p></div><div><span class="muted">Exigible ahora</span><div class="kpi"><?=money($t['due_now'],$cur)?></div></div></div><div class="grid" style="margin-top:18px"><div class="c6"><h3>Materiales</h3><p><span class="muted">Condición:</span> <?=e(implode(' · ',array_keys($t['materials_tax']))?:'—')?><br>Importe presupuestado: <b><?=money($t['materials_input'],$cur)?></b><br>IVA agregado: <b><?=money($t['materials_vat'],$cur)?></b><br>Total con tratamiento de IVA: <b><?=money($t['materials'],$cur)?></b><br>Pagado aplicado: <span class="ok"><?=money($t['materials_paid'],$cur)?></span><br>Saldo de materiales: <b class="bad"><?=money(max(0,$t['materials']-$t['materials_paid']),$cur)?></b></p></div><div class="c6"><h3>Mano de obra e ingeniería</h3><p><span class="muted">Condición:</span> <?=e(implode(' · ',array_keys($t['labor_tax']))?:'—')?><br>Importe presupuestado: <b><?=money($t['labor_input'],$cur)?></b><br>IVA agregado: <b><?=money($t['labor_vat'],$cur)?></b><br>Total con tratamiento de IVA: <b><?=money($t['labor'],$cur)?></b><br>Pagado aplicado (incluye ingeniería): <span class="ok"><?=money($t['labor_paid'],$cur)?></span><br>Saldo de mano de obra: <b class="bad"><?=money(max(0,$t['labor']-$t['labor_paid']),$cur)?></b></p></div></div></div><?php endforeach;?>
<div class="card"><div class="actions"><h2 style="flex:1">Presupuestos</h2><?php if(canManageProjectV2()):?><a class="btn light" href="?a=new_quote&project_id=<?=$id?>">+ Nuevo presupuesto</a><?php endif;?></div><div class="scroll"><table><thead><tr><th>Rubro</th><th>Versión</th><th>Fecha</th><th>Estado</th><th class="right">Materiales</th><th>IVA materiales</th><th class="right">Mano de obra</th><th class="right">Total</th><th>Acciones</th></tr></thead><tbody><?php foreach($quotes as $q):?><tr><td><span class="pill"><?=e($categoryLabels[$q['quote_category']]??$q['quote_category'])?></span></td><td>v<?=e($q['version_no'])?></td><td><?=e(date('d/m/Y',strtotime($q['quote_date'])))?></td><td><span class="pill"><?=e($q['status'])?></span></td><td class="right"><?=money($q['materials_amount'],$q['currency'])?></td><td><?=e($taxLabels[$q['materials_tax_mode']]??$q['materials_tax_mode'])?><?=$q['materials_tax_mode']==='mas_iva'?' '.e($q['materials_vat_rate']).'%':''?></td><td class="right"><?=money($q['labor_amount'],$q['currency'])?></td><td class="right"><b><?=money($q['total'],$q['currency'])?></b></td><td><div class="actions"><a class="btn light" href="?a=quote_view&id=<?=$q['id']?>">Ver</a><a class="btn light" href="?a=edit_quote&id=<?=$q['id']?>">Editar</a></div></td></tr><?php endforeach;?></tbody></table></div></div>
<div class="card"><div class="actions"><h2 style="flex:1">Pagos y recibos</h2><?php if(canManagePaymentsV2()):?><a class="btn" href="?a=new_payment&project_id=<?=$id?>">+ Registrar pago y generar recibo</a><?php endif;?></div><div class="scroll"><table><thead><tr><th>Fecha / recibo</th><th>Medio</th><th>Moneda</th><th class="right">Pago</th><th class="right">Imputado</th><th class="right">Pendiente de imputar</th><th>Acciones</th></tr></thead><tbody><?php foreach($payments as $p):$un=max(0,(float)$p['amount']-(float)$p['allocated']);?><tr><td><?=e(date('d/m/Y',strtotime($p['payment_date'])))?><br><b><?=e($p['receipt_number'])?></b></td><td><?=e($p['method'])?><?=!empty($p['reference'])?' · '.e($p['reference']):''?></td><td><?=e($p['currency'])?></td><td class="right"><b><?=money($p['amount'],$p['currency'])?></b></td><td class="right"><?=money($p['allocated'],$p['currency'])?></td><td class="right"><?=$un>.009?'<b class="bad">'.money($un,$p['currency']).'</b>':money(0,$p['currency'])?></td><td><a class="btn light" target="_blank" href="?a=receipt&id=<?=$p['id']?>">Ver recibo</a></td></tr><?php endforeach;?><?php if(!$payments):?><tr><td colspan="7" class="muted">Todavía no hay pagos registrados.</td></tr><?php endif;?></tbody></table></div></div>
</main></body></html>