<?php
declare(strict_types=1);
if(session_status()!==PHP_SESSION_ACTIVE)session_start();
$root=dirname(__DIR__,3);$cfg=require $root.'/config.php';date_default_timezone_set($cfg['timezone']??'America/Argentina/Buenos_Aires');
if(empty($_SESSION['user'])){header('Location:index.php');exit;}
$db=new PDO('mysql:host='.$cfg['db_host'].';dbname='.$cfg['db_name'].';charset=utf8mb4',$cfg['db_user'],$cfg['db_pass'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
require_once $root.'/app/Core/ProjectFollowup.php';require_once $root.'/app/Core/UnifiedSidebar.php';ensureProjectFollowupSchema($db);
$action=(string)($_GET['a']??'project_followup');$projectId=(int)($_GET['id']??$_POST['project_id']??0);
if(in_array($action,['quote_followup','save_quote_followup'],true)){$quoteId=(int)($_GET['id']??$_POST['quote_id']??0);$q=$db->prepare('SELECT project_id FROM quotes WHERE id=?');$q->execute([$quoteId]);$projectId=(int)$q->fetchColumn();if($action==='quote_followup'&&$projectId){header('Location:?a=project_followup&id='.$projectId);exit;}}
function pfCsrf():void{if(!hash_equals($_SESSION['csrf']??'',(string)($_POST['csrf']??''))){http_response_code(419);exit('Solicitud vencida.');}}
if(in_array($action,['save_project_followup','save_quote_followup'],true)){
 pfCsrf();$id=(int)($_POST['followup_id']??0);$event=(string)($_POST['event_type']??'cliente_contactado');$allowed=['cliente_contactado','reprogramado','nota','cerrado','reabierto'];if(!in_array($event,$allowed,true))$event='nota';
 $method=(string)($_POST['contact_method']??'');if(!in_array($method,['telefono','whatsapp','email','reunion','visita','otro'],true))$method='';
 $result=(string)($_POST['contact_result']??'');if(!in_array($result,['sin_respuesta','interesado','solicita_cambios','volver_a_contactar','aprobado','rechazado','otro'],true))$result='';
 $notes=trim((string)($_POST['notes']??''));$next=trim((string)($_POST['next_contact_date']??''))?:null;$rawWhen=trim((string)($_POST['event_date']??''));$when=$rawWhen!==''?date('Y-m-d H:i:s',strtotime($rawWhen)):date('Y-m-d H:i:s');$userId=(int)($_SESSION['user']['id']??0);
 if($event==='cliente_contactado'&&!$next){
  $automaticDays=['sin_respuesta'=>3,'solicita_cambios'=>3,'interesado'=>5,'volver_a_contactar'=>10];
  if(isset($automaticDays[$result]))$next=projectFollowupBusinessDate(date('Y-m-d',strtotime($when)),$automaticDays[$result]);
 }
 try{$db->beginTransaction();
  if($id){$own=$db->prepare('SELECT id FROM project_followup_history WHERE id=? AND project_id=? AND source_quote_id IS NULL AND legacy_quote_history_id IS NULL');$own->execute([$id,$projectId]);if(!$own->fetchColumn())throw new RuntimeException('Esta gestión automática no se puede modificar.');$db->prepare('UPDATE project_followup_history SET user_id=?,event_type=?,contact_method=?,contact_result=?,next_contact_date=?,notes=?,event_date=? WHERE id=? AND project_id=?')->execute([$userId?:null,$event,$method?:null,$result?:null,$next,$notes?:null,$when,$id,$projectId]);}
  else $db->prepare('INSERT INTO project_followup_history(project_id,user_id,event_type,contact_method,contact_result,next_contact_date,notes,event_date) VALUES(?,?,?,?,?,?,?,?)')->execute([$projectId,$userId?:null,$event,$method?:null,$result?:null,$next,$notes?:null,$when]);
  if($event==='cerrado'||$result==='rechazado')$db->prepare('UPDATE projects SET next_followup_date=NULL,followup_closed_at=NOW(),followup_reminder_sent_at=NULL WHERE id=?')->execute([$projectId]);
  else $db->prepare('UPDATE projects SET followup_responsible_user_id=?,next_followup_date=?,followup_closed_at=NULL,followup_reminder_sent_at=NULL WHERE id=?')->execute([$userId?:null,$next,$projectId]);
  $db->commit();$_SESSION['msg']=$id?'Gestión actualizada.':'Contacto registrado.';
 }catch(Throwable $error){if($db->inTransaction())$db->rollBack();$_SESSION['msg']='No se pudo guardar: '.$error->getMessage();}
 header('Location:?a=project_followup&id='.$projectId);exit;
}
if($action==='delete_project_followup'){
 pfCsrf();$id=(int)($_POST['followup_id']??0);
 try{$db->beginTransaction();$q=$db->prepare('DELETE FROM project_followup_history WHERE id=? AND project_id=? AND source_quote_id IS NULL AND legacy_quote_history_id IS NULL');$q->execute([$id,$projectId]);if(!$q->rowCount())throw new RuntimeException('Esta gestión automática no se puede eliminar.');
  $last=$db->prepare('SELECT next_contact_date,event_type,contact_result FROM project_followup_history WHERE project_id=? ORDER BY event_date DESC,id DESC LIMIT 1');$last->execute([$projectId]);$row=$last->fetch();$closed=$row&&(($row['event_type']??'')==='cerrado'||($row['contact_result']??'')==='rechazado');$db->prepare('UPDATE projects SET next_followup_date=?,followup_closed_at=?,followup_reminder_sent_at=NULL WHERE id=?')->execute([$closed?null:($row['next_contact_date']??null),$closed?date('Y-m-d H:i:s'):null,$projectId]);$db->commit();$_SESSION['msg']='Gestión eliminada.';
 }catch(Throwable $error){if($db->inTransaction())$db->rollBack();$_SESSION['msg']='No se pudo eliminar: '.$error->getMessage();}
 header('Location:?a=project_followup&id='.$projectId);exit;
}
$s=$db->prepare('SELECT p.*,c.business_name,c.contact_name,c.email,c.whatsapp phone,u.name responsible_name FROM projects p JOIN clients c ON c.id=p.client_id LEFT JOIN users u ON u.id=p.followup_responsible_user_id WHERE p.id=?');$s->execute([$projectId]);$project=$s->fetch();if(!$project){http_response_code(404);exit('Proyecto inexistente.');}
$s=$db->prepare('SELECT id,proposal_name,version_no FROM quotes WHERE project_id=? ORDER BY quote_date DESC,id DESC');$s->execute([$projectId]);$quotes=$s->fetchAll();
$s=$db->prepare('SELECT h.*,u.name user_name,q.proposal_name,q.version_no FROM project_followup_history h LEFT JOIN users u ON u.id=h.user_id LEFT JOIN quotes q ON q.id=h.source_quote_id WHERE h.project_id=? ORDER BY h.event_date DESC,h.id DESC');$s->execute([$projectId]);$history=$s->fetchAll();
$edit=null;$editId=(int)($_GET['edit']??0);if($editId){$s=$db->prepare('SELECT * FROM project_followup_history WHERE id=? AND project_id=? AND source_quote_id IS NULL AND legacy_quote_history_id IS NULL');$s->execute([$editId,$projectId]);$edit=$s->fetch()?:null;}
if(empty($_SESSION['csrf']))$_SESSION['csrf']=bin2hex(random_bytes(24));$msg=$_SESSION['msg']??null;unset($_SESSION['msg']);$e=static fn($v):string=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');
$eventLabels=['cliente_contactado'=>'Cliente contactado','reprogramado'=>'Contacto programado','nota'=>'Nota','cerrado'=>'Seguimiento cerrado','reabierto'=>'Seguimiento reabierto','presupuesto_enviado'=>'Presupuesto enviado','enviado'=>'Presupuesto enviado'];$methodLabels=['telefono'=>'Teléfono','whatsapp'=>'WhatsApp','email'=>'Email','reunion'=>'Reunión','visita'=>'Visita','otro'=>'Otro'];$resultLabels=['sin_respuesta'=>'Sin respuesta','interesado'=>'Interesado','solicita_cambios'=>'Solicita cambios','volver_a_contactar'=>'Volver a contactar','aprobado'=>'Aprobado','rechazado'=>'Rechazado','otro'=>'Otro'];
$phone=preg_replace('/\D+/','',(string)$project['phone']);$text='Hola '.($project['contact_name']?:$project['business_name']).', ¿cómo estás? Quería consultarte si pudiste ver la propuesta que te enviamos para el proyecto '.$project['project_number'].' · '.$project['name'].' y si tenés alguna consulta. Quedo atento.';
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Seguimiento · Punto ERP</title><style><?=erpSidebarCss()?>body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.45 system-ui,-apple-system,Segoe UI,sans-serif}.main{margin-left:var(--sidebar);padding:32px 4%}.card{background:#fff;border:1px solid var(--line);border-radius:14px;padding:22px;margin-bottom:18px}.grid{display:grid;grid-template-columns:repeat(12,1fr);gap:14px}.c3{grid-column:span 3}.c4{grid-column:span 4}.c12{grid-column:span 12}.actions{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.btn{display:inline-flex;align-items:center;justify-content:center;border:0;border-radius:8px;padding:9px 13px;background:var(--o);color:#fff;text-decoration:none;font-weight:700;cursor:pointer}.btn.light{background:#edf0f3;color:var(--ink)}.btn.danger{background:#ffe5e5;color:#a92727}.muted{color:var(--muted)}label{display:block;font-weight:700;margin:4px 0 6px}input,select,textarea{width:100%;box-sizing:border-box;padding:10px;border:1px solid var(--line);border-radius:8px}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:10px 8px;border-bottom:1px solid var(--line);vertical-align:top}th{font-size:12px;text-transform:uppercase;color:var(--muted)}.flash{padding:12px;background:#eef8f1;border:1px solid #b9dfc5;border-radius:9px;margin-bottom:16px}.pill{display:inline-block;padding:4px 8px;border-radius:20px;background:#edf0f3;font-size:12px}@media(max-width:900px){.main{margin-left:0;padding:22px 18px}.c3,.c4{grid-column:span 12}}</style></head><body><?php erpSidebar('projects');?><main class="main"><?php if($msg):?><div class="flash"><?=$e($msg)?></div><?php endif;?><div class="actions"><div style="flex:1"><span class="muted">Seguimiento comercial por proyecto</span><h1><?=$e($project['project_number'].' · '.$project['name'])?></h1><p class="muted"><?=$e($project['business_name'])?> · Próximo contacto: <b><?=$project['next_followup_date']?date('d/m/Y',strtotime($project['next_followup_date'])):'sin programar'?></b></p></div><a class="btn light" href="?a=project&id=<?=$projectId?>">Volver al proyecto</a><a class="btn light" href="?a=followup_agenda">Agenda</a></div>
<section class="card"><div class="actions"><div style="flex:1"><h2><?=$edit?'Editar gestión':'Registrar contacto o gestión'?></h2><p class="muted">Indicá qué hiciste y la respuesta. Si elegís Sin respuesta, Solicita cambios, Interesado o Volver a contactar sin fecha, el sistema programará automáticamente el próximo contacto.</p></div><?php if($edit):?><a class="btn light" href="?a=project_followup&id=<?=$projectId?>">Cancelar edición</a><?php endif;?></div><form method="post" action="?a=save_project_followup"><input type="hidden" name="csrf" value="<?=$e($_SESSION['csrf'])?>"><input type="hidden" name="project_id" value="<?=$projectId?>"><input type="hidden" name="followup_id" value="<?=(int)($edit['id']??0)?>"><div class="grid"><p class="c3"><label>Fecha y hora</label><input type="datetime-local" name="event_date" required value="<?=$e(isset($edit['event_date'])?date('Y-m-d\TH:i',strtotime($edit['event_date'])):date('Y-m-d\TH:i'))?>"></p><p class="c3"><label>Tipo de gestión</label><select name="event_type"><?php foreach(['cliente_contactado','reprogramado','nota','cerrado','reabierto'] as $v):?><option value="<?=$v?>" <?=($edit['event_type']??'cliente_contactado')===$v?'selected':''?>><?=$e($eventLabels[$v])?></option><?php endforeach;?></select></p><p class="c3"><label>Medio</label><select name="contact_method"><option value="">No corresponde</option><?php foreach($methodLabels as $v=>$label):?><option value="<?=$v?>" <?=($edit['contact_method']??'')===$v?'selected':''?>><?=$e($label)?></option><?php endforeach;?></select></p><p class="c3"><label>Resultado</label><select name="contact_result"><option value="">Sin resultado</option><?php foreach($resultLabels as $v=>$label):?><option value="<?=$v?>" <?=($edit['contact_result']??'')===$v?'selected':''?>><?=$e($label)?></option><?php endforeach;?></select></p><p class="c4"><label>Volver a contactar</label><input type="date" name="next_contact_date" value="<?=$e($edit['next_contact_date']??$project['next_followup_date']??'')?>"></p><p class="c12"><label>Detalle / respuesta del cliente</label><textarea name="notes" rows="4" placeholder="Ej.: Le interesó, pidió revisar materiales y volver a llamar el viernes."><?=$e($edit['notes']??'')?></textarea></p></div><div class="actions"><button class="btn" type="submit"><?=$edit?'Guardar cambios':'Registrar gestión'?></button><?php if($phone):?><a class="btn light" target="_blank" href="https://wa.me/<?=$e($phone)?>?text=<?=rawurlencode($text)?>">Abrir WhatsApp</a><?php endif;?><?php if($project['email']):?><a class="btn light" href="mailto:<?=$e($project['email'])?>?subject=<?=rawurlencode('Seguimiento del proyecto '.$project['project_number'])?>&body=<?=rawurlencode($text)?>">Enviar email</a><?php endif;?></div></form></section>
<section class="card"><h2>Historial de gestiones</h2><div style="overflow:auto"><table><tr><th>Fecha</th><th>Gestión</th><th>Medio</th><th>Resultado</th><th>Detalle</th><th>Próximo</th><th>Usuario</th><th>Acciones</th></tr><?php foreach($history as $h):$manual=empty($h['source_quote_id'])&&empty($h['legacy_quote_history_id']);?><tr><td><?=date('d/m/Y H:i',strtotime($h['event_date']))?></td><td><b><?=$e($eventLabels[$h['event_type']]??str_replace('_',' ',$h['event_type']))?></b><?php if($h['source_quote_id']):?><br><small class="muted"><?=$e((trim((string)$h['proposal_name'])?:'Presupuesto').' · v'.$h['version_no'])?></small><?php endif;?></td><td><?=$e($methodLabels[$h['contact_method']]??'—')?></td><td><?=$h['contact_result']?'<span class="pill">'.$e($resultLabels[$h['contact_result']]??$h['contact_result']).'</span>':'—'?></td><td><?=$e($h['notes']?:'—')?></td><td><?=$h['next_contact_date']?date('d/m/Y',strtotime($h['next_contact_date'])):'—'?></td><td><?=$e($h['user_name']?:'Sistema')?></td><td><?php if($manual):?><div class="actions"><a class="btn light" href="?a=project_followup&id=<?=$projectId?>&edit=<?=(int)$h['id']?>">Editar</a><form method="post" action="?a=delete_project_followup" onsubmit="return confirm('¿Eliminar esta gestión?')"><input type="hidden" name="csrf" value="<?=$e($_SESSION['csrf'])?>"><input type="hidden" name="project_id" value="<?=$projectId?>"><input type="hidden" name="followup_id" value="<?=(int)$h['id']?>"><button class="btn danger" type="submit">Eliminar</button></form></div><?php else:?><span class="muted">Automático</span><?php endif;?></td></tr><?php endforeach;?><?php if(!$history):?><tr><td colspan="8" class="muted">Todavía no hay gestiones registradas.</td></tr><?php endif;?></table></div></section>
<section class="card"><h2>Presupuestos del proyecto</h2><div class="actions"><?php foreach($quotes as $q):?><a class="btn light" href="?a=quote_view&id=<?=(int)$q['id']?>"><?=$e((trim((string)$q['proposal_name'])?:'Presupuesto').' · v'.$q['version_no'])?></a><?php endforeach;?><?php if(!$quotes):?><span class="muted">Sin presupuestos.</span><?php endif;?></div></section></main></body></html>
