<?php
declare(strict_types=1);
session_start();
$root=dirname(__DIR__,3);$cfg=require $root.'/config.php';date_default_timezone_set($cfg['timezone']??'America/Argentina/Buenos_Aires');
if(empty($_SESSION['user'])){header('Location:index.php');exit;}
$db=new PDO('mysql:host='.$cfg['db_host'].';dbname='.$cfg['db_name'].';charset=utf8mb4',$cfg['db_user'],$cfg['db_pass'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
require_once $root.'/app/Core/UnifiedSidebar.php';
function et($v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function tCanManage():bool{if(($_SESSION['user']['role']??'')==='admin')return true;$p=$_SESSION['user']['permissions']??[];return !empty($p['technical_projects']['manage']);}
function tCanView():bool{if(($_SESSION['user']['role']??'')==='admin')return true;$p=$_SESSION['user']['permissions']??[];return !empty($p['technical_projects']['view'])||!empty($p['technical_projects']['manage']);}
if(!tCanView()){http_response_code(403);exit('No tenés permiso para ver Proyectos técnicos.');}
$statuses=['pendiente_planificacion'=>'Pendiente de planificación','planificado'=>'Planificado','en_instalacion'=>'En instalación','esperando_material'=>'Esperando material','esperando_terceros'=>'Esperando terceros','puesta_en_marcha'=>'Puesta en marcha','finalizado'=>'Finalizado'];
$a=$_GET['a']??'technical_projects';
if($a==='save_technical_project'){
 if(!tCanManage()){http_response_code(403);exit('No tenés permiso para administrar Proyectos técnicos.');}
 $id=(int)($_POST['project_id']??0);$manager=(int)($_POST['manager_user_id']??0);$status=(string)($_POST['technical_status']??'pendiente_planificacion');$members=array_values(array_unique(array_filter(array_map('intval',(array)($_POST['technical_users']??[])))));
 if(!isset($statuses[$status]))$status='pendiente_planificacion';
 $db->beginTransaction();try{$db->prepare('UPDATE projects SET technical_status=?,technical_manager_user_id=? WHERE id=?')->execute([$status,$manager?:null,$id]);$db->prepare('DELETE FROM project_technical_users WHERE project_id=?')->execute([$id]);$ins=$db->prepare('INSERT INTO project_technical_users(project_id,user_id,assigned_by_user_id) VALUES(?,?,?)');foreach($members as $uid)$ins->execute([$id,$uid,(int)($_SESSION['user']['id']??0)?:null]);$db->commit();$_SESSION['msg']='Proyecto técnico actualizado.';}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}header('Location:?a=technical_project&id='.$id);exit;
}
if($a==='technical_projects'){
 $where=[];$args=[];if(!tCanManage()){$uid=(int)($_SESSION['user']['id']??0);$where[]='(p.technical_manager_user_id=? OR EXISTS(SELECT 1 FROM project_technical_users ptu WHERE ptu.project_id=p.id AND ptu.user_id=?))';$args=[$uid,$uid];}
 $sql='SELECT p.id,p.project_number,p.name,p.technical_status,p.created_at,c.business_name,u.name manager_name,(SELECT COUNT(*) FROM project_technical_users x WHERE x.project_id=p.id) team_count FROM projects p JOIN clients c ON c.id=p.client_id LEFT JOIN users u ON u.id=p.technical_manager_user_id'.($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY p.created_at DESC,p.id DESC';$s=$db->prepare($sql);$s->execute($args);$rows=$s->fetchAll();
 ?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Proyectos técnicos · Punto ERP</title><style><?=erpSidebarCss()?>body{margin:0;background:var(--bg);color:var(--ink);font:15px system-ui}.main{margin-left:var(--sidebar);padding:32px 4%}.card{background:#fff;border:1px solid var(--line);border-radius:14px;padding:22px}.muted{color:var(--muted)}table{width:100%;border-collapse:collapse}th,td{padding:12px 10px;border-bottom:1px solid var(--line);text-align:left}th{font-size:12px;text-transform:uppercase;color:var(--muted)}.btn{display:inline-block;padding:9px 13px;border-radius:8px;background:#edf0f3;color:var(--ink);font-weight:700;text-decoration:none}.pill{padding:4px 9px;border-radius:20px;background:#fff1e8;font-size:12px}@media(max-width:900px){.main{margin-left:0;padding:20px 14px}.card{overflow:auto}}</style></head><body><?php erpSidebar('technical_projects');?><main class="main"><h1>Proyectos técnicos</h1><p class="muted">Vista de ejecución de obra. No muestra precios, costos, cobros ni saldos.</p><div class="card"><table><thead><tr><th>Proyecto</th><th>Cliente</th><th>Estado técnico</th><th>Responsable</th><th>Equipo</th><th></th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><b><?=et($r['project_number'])?></b><br><?=et($r['name'])?></td><td><?=et($r['business_name'])?></td><td><span class="pill"><?=et($statuses[$r['technical_status']]??$r['technical_status'])?></span></td><td><?=et($r['manager_name']?:'Sin asignar')?></td><td><?=et($r['team_count'])?> técnico(s)</td><td><a class="btn" href="?a=technical_project&id=<?=$r['id']?>">Abrir</a></td></tr><?php endforeach;?></tbody></table></div></main></body></html><?php exit;
}
$id=(int)($_GET['id']??0);$s=$db->prepare('SELECT p.*,c.business_name,c.city,c.province,pp.business_name partner_name,u.name manager_name FROM projects p JOIN clients c ON c.id=p.client_id LEFT JOIN project_partners pp ON pp.id=p.partner_id LEFT JOIN users u ON u.id=p.technical_manager_user_id WHERE p.id=?');$s->execute([$id]);$p=$s->fetch();if(!$p){http_response_code(404);exit('Proyecto inexistente.');}
if(!tCanManage()){$uid=(int)($_SESSION['user']['id']??0);$s=$db->prepare('SELECT 1 FROM project_technical_users WHERE project_id=? AND user_id=? UNION SELECT 1 FROM projects WHERE id=? AND technical_manager_user_id=? LIMIT 1');$s->execute([$id,$uid,$id,$uid]);if(!$s->fetchColumn()){http_response_code(403);exit('Este proyecto no está asignado a tu usuario.');}}
$qs=$db->prepare("SELECT * FROM quotes WHERE project_id=? AND status NOT IN ('rechazado') ORDER BY FIELD(status,'final','aprobado_inicial','enviado','borrador'),version_no DESC,id DESC");$qs->execute([$id]);$quotes=$qs->fetchAll();$quote=$quotes[0]??null;$items=[];$labor=[];if($quote){$x=$db->prepare('SELECT qi.*,pr.image_data,pr.image_mime FROM quote_items qi LEFT JOIN products pr ON pr.id=qi.product_id WHERE qi.quote_id=? ORDER BY qi.block_order,qi.sort_order,qi.id');$x->execute([$quote['id']]);$items=$x->fetchAll();try{$x=$db->prepare('SELECT * FROM quote_labor_items WHERE quote_id=? ORDER BY block_order,id');$x->execute([$quote['id']]);$labor=$x->fetchAll();}catch(Throwable $e){}}
$team=$db->prepare('SELECT u.id,u.name,u.email FROM project_technical_users ptu JOIN users u ON u.id=ptu.user_id WHERE ptu.project_id=? ORDER BY u.name');$team->execute([$id]);$teamRows=$team->fetchAll();$users=[];if(tCanManage()){$users=$db->query("SELECT u.id,u.name,u.email,up.area FROM users u LEFT JOIN user_profiles up ON up.id=u.profile_id WHERE u.active=1 ORDER BY (up.area='tecnico') DESC,u.name")->fetchAll();}
$msg=$_SESSION['msg']??null;unset($_SESSION['msg']);
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=et($p['project_number'])?> · Proyecto técnico</title><style><?=erpSidebarCss()?>body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.45 system-ui}.main{margin-left:var(--sidebar);padding:32px 4%}.card{background:#fff;border:1px solid var(--line);border-radius:14px;padding:22px;margin-bottom:18px}.grid{display:grid;grid-template-columns:repeat(12,1fr);gap:16px}.c6{grid-column:span 6}.muted{color:var(--muted)}.pill{display:inline-block;padding:5px 10px;border-radius:20px;background:#fff1e8}.btn{border:0;border-radius:8px;padding:10px 15px;background:var(--o);color:#fff;text-decoration:none;font-weight:700;cursor:pointer}.btn.light{background:#edf0f3;color:var(--ink)}table{width:100%;border-collapse:collapse}th,td{padding:11px 9px;border-bottom:1px solid var(--line);text-align:left;vertical-align:middle}th{font-size:12px;text-transform:uppercase;color:var(--muted)}.pic{width:48px}.pic img{width:42px;height:42px;object-fit:contain}.section td{font-weight:800;background:#f5f6f7}.checks{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.check{padding:9px;border:1px solid var(--line);border-radius:8px}select{width:100%;padding:10px;border:1px solid var(--line);border-radius:8px;background:#fff}.flash{padding:12px;background:#eefaf5;border:1px solid #bfe8d4;border-radius:8px;margin-bottom:15px}@media(max-width:900px){.main{margin-left:0;padding:20px 14px}.c6{grid-column:span 12}.checks{grid-template-columns:1fr}.card{overflow:auto}}</style></head><body><?php erpSidebar('technical_projects');?><main class="main"><?php if($msg):?><div class="flash"><?=et($msg)?></div><?php endif;?><div><span class="muted"><?=et($p['business_name'])?></span><h1 style="margin:.2em 0"><?=et($p['project_number'])?> · <?=et($p['name'])?></h1><span class="pill"><?=et($statuses[$p['technical_status']]??$p['technical_status'])?></span></div><div class="grid" style="margin-top:18px"><div class="card c6"><h2>Información de obra</h2><p><b>Cliente:</b> <?=et($p['business_name'])?><br><b>Ubicación:</b> <?=et(trim(($p['city']??'').' '.($p['province']??'')))?><br><b>Arquitecto / constructora:</b> <?=et($p['partner_name']?:'—')?><br><b>Responsable técnico:</b> <?=et($p['manager_name']?:'Sin asignar')?></p></div><div class="card c6"><h2>Equipo técnico</h2><?php if($teamRows):?><ul><?php foreach($teamRows as $u):?><li><?=et($u['name'])?></li><?php endforeach;?></ul><?php else:?><p class="muted">Todavía no hay técnicos asignados.</p><?php endif;?></div></div>
<?php if(tCanManage()):?><div class="card"><h2>Administrar proyecto técnico</h2><form method="post" action="?a=save_technical_project"><input type="hidden" name="project_id" value="<?=$id?>"><div class="grid"><div class="c6"><label><b>Estado técnico</b></label><select name="technical_status"><?php foreach($statuses as $k=>$v):?><option value="<?=et($k)?>" <?=$p['technical_status']===$k?'selected':''?>><?=et($v)?></option><?php endforeach;?></select></div><div class="c6"><label><b>Project Manager / responsable</b></label><select name="manager_user_id"><option value="">Sin asignar</option><?php foreach($users as $u):?><option value="<?=$u['id']?>" <?=(int)$p['technical_manager_user_id']===(int)$u['id']?'selected':''?>><?=et($u['name'])?><?=!empty($u['area'])?' · '.et($u['area']):''?></option><?php endforeach;?></select></div></div><h3>Técnicos asignados</h3><div class="checks"><?php $selected=array_map(fn($x)=>(int)$x['id'],$teamRows);foreach($users as $u):?><label class="check"><input type="checkbox" name="technical_users[]" value="<?=$u['id']?>" <?=in_array((int)$u['id'],$selected,true)?'checked':''?>> <?=et($u['name'])?><?=!empty($u['area'])?' · '.et($u['area']):''?></label><?php endforeach;?></div><p><button class="btn" type="submit">Guardar asignación</button></p></form></div><?php endif;?>
<div class="card"><div style="display:flex;align-items:center;gap:10px"><h2 style="flex:1">Equipamiento vendido</h2><?php if($quote):?><a class="btn light" href="?a=technical_quote&id=<?=$quote['id']?>">Ver detalle / PDF técnico</a><?php endif;?></div><?php if(!$quote):?><p class="muted">Este proyecto todavía no tiene presupuesto.</p><?php else:?><table><thead><tr><th>Imagen</th><th>SKU</th><th>Descripción</th><th>Cantidad</th></tr></thead><tbody><?php $last=null;foreach($items as $it):$sec=$it['section_title']?:'Materiales';if($sec!==$last):$last=$sec;?><tr class="section"><td colspan="4"><?=et($sec)?></td></tr><?php endif;?><tr><td class="pic"><?php if(!empty($it['image_data'])&&!empty($it['image_mime'])):?><img src="data:<?=et($it['image_mime'])?>;base64,<?=base64_encode($it['image_data'])?>"><?php endif;?></td><td><b><?=et($it['sku'])?></b></td><td><?=et($it['description'])?></td><td><?=et(rtrim(rtrim(number_format((float)$it['quantity'],2,'.',''),'0'),'.'))?></td></tr><?php endforeach;?><?php foreach($labor as $l):?><tr class="section"><td colspan="4"><?=et($l['title'])?></td></tr><tr><td></td><td colspan="3"><?=et($l['description'])?></td></tr><?php endforeach;?></tbody></table><?php endif;?></div></main></body></html>