<?php
declare(strict_types=1);
session_start();
$root=dirname(__DIR__,3);$cfg=require $root.'/config.php';date_default_timezone_set($cfg['timezone']??'America/Argentina/Buenos_Aires');
$db=new PDO('mysql:host='.$cfg['db_host'].';dbname='.$cfg['db_name'].';charset=utf8mb4',$cfg['db_user'],$cfg['db_pass'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
if(empty($_SESSION['user'])){header('Location:index.php');exit;}
$_SESSION['csrf']??=bin2hex(random_bytes(24));
require_once $root.'/app/Core/UnifiedSidebar.php';
function e($v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function money($n,string $cur='USD'):string{return ($cur==='USD'?'US$ ':'$ ').number_format((float)$n,2,',','.');}
function go(string $u):never{header('Location:'.$u);exit;}
function csrf():void{if(!hash_equals($_SESSION['csrf']??'',$_POST['csrf']??'')){http_response_code(419);exit('Solicitud vencida.');}}
function canManagePayments():bool{if(($_SESSION['user']['role']??'')==='admin')return true;$p=$_SESSION['user']['permissions']??[];return !empty($p['payments']['manage'])||!empty($p['receipts']['manage']);}
function chargeRows(PDO $db,int $projectId,string $currency,int $paymentId=0):array{
 $sql="SELECT c.id,c.type,c.description,c.amount,c.charge_date,c.currency,
 COALESCE(SUM(CASE WHEN a.payment_id<>? THEN a.amount ELSE 0 END),0) paid_other,
 COALESCE(SUM(CASE WHEN a.payment_id=? THEN a.amount ELSE 0 END),0) paid_this
 FROM charges c LEFT JOIN allocations a ON a.charge_id=c.id
 WHERE c.project_id=? AND c.currency=? AND c.active=1
 GROUP BY c.id ORDER BY FIELD(c.type,'ingenieria','mano_obra','materiales','adicional','ajuste'),c.charge_date,c.id";
 $s=$db->prepare($sql);$s->execute([$paymentId,$paymentId,$projectId,$currency]);return $s->fetchAll();
}
function buildAllocations(array $rows,array $posted,float $amount):array{
 $open=[];$alloc=[];
 foreach($rows as $c){$max=max(0,(float)$c['amount']-(float)$c['paid_other']);$open[(int)$c['id']]=$max;}
 foreach($posted as $cid=>$value){$cid=(int)$cid;$value=(float)$value;if($value<=0)continue;if(!isset($open[$cid]))throw new Exception('Uno de los cargos ya no está disponible.');if($value>$open[$cid]+.001)throw new Exception('La imputación supera el pendiente del cargo.');$alloc[$cid]=$value;}
 if(array_sum($alloc)>$amount+.001)throw new Exception('La imputación supera el importe del pago.');
 $remaining=$amount-array_sum($alloc);foreach($open as $cid=>$due){if($remaining<=.009)break;$available=$due-($alloc[$cid]??0);if($available<=.009)continue;$auto=min($available,$remaining);$alloc[$cid]=($alloc[$cid]??0)+$auto;$remaining-=$auto;}
 return $alloc;
}
$a=$_GET['a']??'receipts';
try{
 if($a==='save_payment_general'){
  if(!canManagePayments())throw new Exception('Tu perfil no permite registrar pagos.');csrf();
  $pid=(int)($_POST['project_id']??0);$currency=$_POST['currency']??'USD';$amount=(float)($_POST['amount']??0);$date=$_POST['payment_date']??date('Y-m-d');$method=$_POST['method']??'transferencia';
  if(!$pid||!in_array($currency,['ARS','USD'],true)||$amount<=0)throw new Exception('Revisá proyecto, moneda e importe.');
  $rows=chargeRows($db,$pid,$currency,0);$alloc=buildAllocations($rows,$_POST['alloc']??[],$amount);
  $db->beginTransaction();$token=bin2hex(random_bytes(24));
  $db->prepare('INSERT INTO payments(project_id,currency,payment_date,amount,method,reference,notes,public_token) VALUES(?,?,?,?,?,?,?,?)')->execute([$pid,$currency,$date,$amount,$method,trim((string)($_POST['reference']??'')),trim((string)($_POST['notes']??'')),$token]);
  $pay=(int)$db->lastInsertId();$receipt='REC-'.date('Y',strtotime($date)).'-'.str_pad((string)$pay,6,'0',STR_PAD_LEFT);$db->prepare('UPDATE payments SET receipt_number=? WHERE id=?')->execute([$receipt,$pay]);
  $ins=$db->prepare('INSERT INTO allocations(payment_id,charge_id,amount) VALUES(?,?,?)');foreach($alloc as $cid=>$v)$ins->execute([$pay,$cid,$v]);$db->commit();$_SESSION['msg']='Pago '.$receipt.' registrado.';go('?a=receipts');
 }
 if($a==='update_payment'){
  if(!canManagePayments())throw new Exception('Tu perfil no permite editar pagos.');csrf();$id=(int)($_POST['payment_id']??0);
  $s=$db->prepare('SELECT * FROM payments WHERE id=?');$s->execute([$id]);$p=$s->fetch();if(!$p)throw new Exception('Pago inexistente.');
  $currency=$_POST['currency']??$p['currency'];$amount=(float)($_POST['amount']??0);$date=$_POST['payment_date']??$p['payment_date'];$method=$_POST['method']??$p['method'];if($amount<=0||!in_array($currency,['ARS','USD'],true))throw new Exception('Revisá moneda e importe.');
  $rows=chargeRows($db,(int)$p['project_id'],$currency,$id);$alloc=buildAllocations($rows,$_POST['alloc']??[],$amount);
  $db->beginTransaction();$db->prepare('DELETE FROM allocations WHERE payment_id=?')->execute([$id]);
  $db->prepare('UPDATE payments SET currency=?,payment_date=?,amount=?,method=?,reference=?,notes=? WHERE id=?')->execute([$currency,$date,$amount,$method,trim((string)($_POST['reference']??'')),trim((string)($_POST['notes']??'')),$id]);
  $ins=$db->prepare('INSERT INTO allocations(payment_id,charge_id,amount) VALUES(?,?,?)');foreach($alloc as $cid=>$v)$ins->execute([$id,$cid,$v]);$db->commit();$_SESSION['msg']='Pago '.$p['receipt_number'].' actualizado.';go('?a=receipts');
 }
}catch(Throwable $ex){if($db->inTransaction())$db->rollBack();$_SESSION['msg']='No se pudo guardar: '.$ex->getMessage();go($_SERVER['HTTP_REFERER']??'?a=receipts');}
$msg=$_SESSION['msg']??null;unset($_SESSION['msg']);
$projects=$db->query('SELECT p.id,p.project_number,p.name,c.business_name FROM projects p JOIN clients c ON c.id=p.client_id WHERE p.status<>"cancelado" ORDER BY p.created_at DESC')->fetchAll();
function pageStart(string $title,string $current='receipts'):void{global $msg;?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($title)?> · Punto ERP</title><style><?=erpSidebarCss()?>body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.45 system-ui,-apple-system,Segoe UI,sans-serif}.main{margin-left:var(--sidebar);padding:32px 4%}.card{background:#fff;border:1px solid var(--line);border-radius:14px;padding:22px;margin-bottom:18px;box-shadow:0 4px 16px #00000008}.row{display:flex;gap:12px;align-items:center;flex-wrap:wrap}.actions{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.btn{display:inline-flex;align-items:center;justify-content:center;border:0;border-radius:8px;padding:10px 14px;background:var(--o);color:#fff;text-decoration:none;font-weight:700;cursor:pointer}.btn.light{background:#edf0f3;color:var(--ink)}.muted{color:var(--muted)}.flash{padding:12px 15px;background:#fff0e5;border:1px solid #ffd2b1;border-radius:9px;margin-bottom:18px}.grid{display:grid;grid-template-columns:repeat(12,1fr);gap:16px}.c3{grid-column:span 3}.c4{grid-column:span 4}.c6{grid-column:span 6}.c12{grid-column:span 12}label{display:block;font-weight:650;margin-bottom:6px}input,select,textarea{width:100%;padding:10px 11px;border:1px solid #cbd1d7;border-radius:8px;background:#fff;font:inherit}textarea{min-height:80px}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:11px 9px;border-bottom:1px solid var(--line);vertical-align:top}th{font-size:12px;text-transform:uppercase;color:var(--muted)}.right{text-align:right}.pill{display:inline-block;padding:4px 9px;border-radius:20px;background:#edf0f3;font-size:12px}.scroll{overflow:auto}.bad{color:#bf3c3c}@media(max-width:900px){.main{margin-left:0;padding:22px 18px}.c3,.c4,.c6{grid-column:span 12}}</style></head><body><?php erpSidebar($current);?><main class="main"><?php if($msg):?><div class="flash"><?=e($msg)?></div><?php endif;}
function pageEnd():void{?></main></body></html><?php }
if($a==='receipts'){
 $rows=$db->query('SELECT pa.*,pr.project_number,pr.name project_name,c.business_name,c.email,c.whatsapp,COALESCE((SELECT SUM(a.amount) FROM allocations a WHERE a.payment_id=pa.id),0) allocated FROM payments pa JOIN projects pr ON pr.id=pa.project_id JOIN clients c ON c.id=pr.client_id ORDER BY pa.payment_date DESC,pa.id DESC')->fetchAll();pageStart('Recibos y pagos');?>
 <div class="row"><div style="flex:1"><h1>Recibos y pagos</h1><p class="muted">Administrá todos los pagos desde acá o desde el detalle de cada proyecto.</p></div><?php if(canManagePayments()):?><a class="btn" href="?a=payment_new_general">+ Nuevo pago</a><?php endif;?></div>
 <div class="card scroll"><table><thead><tr><th>Recibo / fecha</th><th>Cliente</th><th>Proyecto</th><th>Moneda</th><th class="right">Pago</th><th class="right">Imputado</th><th class="right">Pendiente</th><th>Acciones</th></tr></thead><tbody><?php foreach($rows as $r):$pending=max(0,(float)$r['amount']-(float)$r['allocated']);?><tr><td><b><?=e($r['receipt_number'])?></b><br><?=e(date('d/m/Y',strtotime($r['payment_date'])))?></td><td><?=e($r['business_name'])?></td><td><a href="?a=project&id=<?=$r['project_id']?>"><?=e($r['project_number'].' · '.$r['project_name'])?></a></td><td><span class="pill"><?=e($r['currency'])?></span></td><td class="right"><b><?=money($r['amount'],$r['currency'])?></b></td><td class="right"><?=money($r['allocated'],$r['currency'])?></td><td class="right"><?=$pending>.009?'<b class="bad">'.money($pending,$r['currency']).'</b>':money(0,$r['currency'])?></td><td><div class="actions"><a class="btn light" target="_blank" href="?a=receipt&id=<?=$r['id']?>">Ver / imprimir</a><?php if(canManagePayments()):?><a class="btn light" href="?a=edit_payment&id=<?=$r['id']?>">Editar</a><?php endif;?><?php if($r['email']):?><form method="post" action="?a=send_receipt_email" style="margin:0"><input type="hidden" name="csrf" value="<?=e($_SESSION['csrf'])?>"><input type="hidden" name="payment_id" value="<?=$r['id']?>"><button class="btn light">Email</button></form><?php endif;?><?php if($r['whatsapp']):?><a class="btn light" target="_blank" href="?a=receipt_whatsapp&id=<?=$r['id']?>">WhatsApp</a><?php endif;?></div></td></tr><?php endforeach;?><?php if(!$rows):?><tr><td colspan="8" class="muted">Todavía no hay pagos registrados.</td></tr><?php endif;?></tbody></table></div><?php pageEnd();exit;
}
if($a==='payment_new_general'){
 $pid=(int)($_GET['project_id']??0);if(!$pid){pageStart('Nuevo pago');?><div class="card"><h1>Nuevo pago</h1><p class="muted">Elegí el proyecto al que corresponde el pago.</p><form method="get"><input type="hidden" name="a" value="payment_new_general"><p><label>Proyecto</label><select name="project_id" required><option value="">Seleccionar…</option><?php foreach($projects as $pr):?><option value="<?=$pr['id']?>"><?=e($pr['project_number'].' · '.$pr['business_name'].' · '.$pr['name'])?></option><?php endforeach;?></select></p><button class="btn">Continuar</button> <a class="btn light" href="?a=receipts">Cancelar</a></form></div><?php pageEnd();exit;}
 $s=$db->prepare('SELECT p.*,c.business_name FROM projects p JOIN clients c ON c.id=p.client_id WHERE p.id=?');$s->execute([$pid]);$pr=$s->fetch();if(!$pr)exit('Proyecto inexistente.');$currency='USD';$charges=chargeRows($db,$pid,$currency,0);pageStart('Nuevo pago');?>
 <div class="card"><div class="row"><div style="flex:1"><h1>Nuevo pago</h1><p class="muted"><?=e($pr['project_number'].' · '.$pr['business_name'].' · '.$pr['name'])?></p></div><a class="btn light" href="?a=receipts">Cancelar</a></div><form method="post" action="?a=save_payment_general"><input type="hidden" name="csrf" value="<?=e($_SESSION['csrf'])?>"><input type="hidden" name="project_id" value="<?=$pid?>"><div class="grid"><p class="c3"><label>Fecha</label><input type="date" name="payment_date" value="<?=date('Y-m-d')?>" required></p><p class="c3"><label>Moneda</label><select name="currency"><option value="USD" selected>USD</option><option value="ARS">ARS</option></select></p><p class="c3"><label>Importe</label><input type="number" min=".01" step=".01" name="amount" required></p><p class="c3"><label>Medio</label><select name="method"><option value="transferencia">Transferencia</option><option value="efectivo">Efectivo</option><option value="cheque">Cheque</option><option value="tarjeta">Tarjeta</option><option value="otro">Otro</option></select></p><p class="c6"><label>Referencia</label><input name="reference"></p><p class="c6"><label>Notas</label><textarea name="notes"></textarea></p></div><h3>Imputación</h3><p class="muted">Podés indicar los importes manualmente. Lo que quede libre se imputa automáticamente por prioridad: ingeniería, mano de obra, materiales.</p><table><tr><th>Concepto</th><th class="right">Pendiente</th><th style="width:220px">Asignar</th></tr><?php foreach($charges as $c):$due=max(0,(float)$c['amount']-(float)$c['paid_other']);?><tr><td><span class="pill"><?=e($c['type'])?></span> <?=e($c['description'])?></td><td class="right"><?=money($due,$c['currency'])?></td><td><input type="number" min="0" max="<?=$due?>" step=".01" name="alloc[<?=$c['id']?>]" value="0"></td></tr><?php endforeach;?></table><br><button class="btn">Guardar pago y generar recibo</button></form></div><?php pageEnd();exit;
}
if($a==='edit_payment'){
 $id=(int)($_GET['id']??0);$s=$db->prepare('SELECT pa.*,pr.project_number,pr.name project_name,c.business_name FROM payments pa JOIN projects pr ON pr.id=pa.project_id JOIN clients c ON c.id=pr.client_id WHERE pa.id=?');$s->execute([$id]);$p=$s->fetch();if(!$p)exit('Pago inexistente.');$charges=chargeRows($db,(int)$p['project_id'],(string)$p['currency'],$id);pageStart('Editar pago');?>
 <div class="card"><div class="row"><div style="flex:1"><h1>Editar pago</h1><p class="muted"><?=e($p['receipt_number'].' · '.$p['project_number'].' · '.$p['business_name'].' · '.$p['project_name'])?></p></div><a class="btn light" href="?a=receipts">Cancelar</a></div><form method="post" action="?a=update_payment"><input type="hidden" name="csrf" value="<?=e($_SESSION['csrf'])?>"><input type="hidden" name="payment_id" value="<?=$id?>"><div class="grid"><p class="c3"><label>Fecha</label><input type="date" name="payment_date" value="<?=e($p['payment_date'])?>" required></p><p class="c3"><label>Moneda</label><select name="currency"><option value="USD" <?=$p['currency']==='USD'?'selected':''?>>USD</option><option value="ARS" <?=$p['currency']==='ARS'?'selected':''?>>ARS</option></select></p><p class="c3"><label>Importe</label><input type="number" min=".01" step=".01" name="amount" value="<?=e($p['amount'])?>" required></p><p class="c3"><label>Medio</label><select name="method"><?php foreach(['transferencia'=>'Transferencia','efectivo'=>'Efectivo','cheque'=>'Cheque','tarjeta'=>'Tarjeta','otro'=>'Otro'] as $v=>$l):?><option value="<?=$v?>" <?=$p['method']===$v?'selected':''?>><?=$l?></option><?php endforeach;?></select></p><p class="c6"><label>Referencia</label><input name="reference" value="<?=e($p['reference'])?>"></p><p class="c6"><label>Notas</label><textarea name="notes"><?=e($p['notes'])?></textarea></p></div><h3>Imputación del pago</h3><table><tr><th>Concepto</th><th class="right">Disponible</th><th style="width:220px">Asignado</th></tr><?php foreach($charges as $c):$max=max(0,(float)$c['amount']-(float)$c['paid_other']);?><tr><td><span class="pill"><?=e($c['type'])?></span> <?=e($c['description'])?></td><td class="right"><?=money($max,$c['currency'])?></td><td><input type="number" min="0" max="<?=$max?>" step=".01" name="alloc[<?=$c['id']?>]" value="<?=e($c['paid_this'])?>"></td></tr><?php endforeach;?></table><br><button class="btn">Guardar cambios</button></form></div><?php pageEnd();exit;
}
go('?a=receipts');
