name: Validar PHP

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  php-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Validar sintaxis PHP
        run: find . -type f -name '*.php' -not -path './.git/*' -print0 | xargs -0 -n1 php -l

